# Continuous Control

---

In this notebook, you will learn how to use the Unity ML-Agents environment for the second project of the [Deep Reinforcement Learning Nanodegree](https://www.udacity.com/course/deep-reinforcement-learning-nanodegree--nd893) program.

### 1. Start the Environment

We begin by importing the necessary packages.  If the code cell below returns an error, please revisit the project instructions to double-check that you have installed [Unity ML-Agents](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Installation.md) and [NumPy](http://www.numpy.org/).

In [1]:
from unityagents import UnityEnvironment
import numpy as np
import torch

Next, we will start the environment!  **_Before running the code cell below_**, change the `file_name` parameter to match the location of the Unity environment that you downloaded.

- **Mac**: `"path/to/Reacher.app"`
- **Windows** (x86): `"path/to/Reacher_Windows_x86/Reacher.exe"`
- **Windows** (x86_64): `"path/to/Reacher_Windows_x86_64/Reacher.exe"`
- **Linux** (x86): `"path/to/Reacher_Linux/Reacher.x86"`
- **Linux** (x86_64): `"path/to/Reacher_Linux/Reacher.x86_64"`
- **Linux** (x86, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86"`
- **Linux** (x86_64, headless): `"path/to/Reacher_Linux_NoVis/Reacher.x86_64"`

For instance, if you are using a Mac, then you downloaded `Reacher.app`.  If this file is in the same folder as the notebook, then the line below should appear as follows:
```
env = UnityEnvironment(file_name="Reacher.app")
```

In [2]:
env = UnityEnvironment(file_name='Reacher.exe')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		goal_speed -> 1.0
		goal_size -> 5.0
Unity brain name: ReacherBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 33
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


Environments contain **_brains_** which are responsible for deciding the actions of their associated agents. Here we check for the first brain available, and set it as the default brain we will be controlling from Python.

In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

### 2. Examine the State and Action Spaces

In this environment, a double-jointed arm can move to target locations. A reward of `+0.1` is provided for each step that the agent's hand is in the goal location. Thus, the goal of your agent is to maintain its position at the target location for as many time steps as possible.

The observation space consists of `33` variables corresponding to position, rotation, velocity, and angular velocities of the arm.  Each action is a vector with four numbers, corresponding to torque applicable to two joints.  Every entry in the action vector must be a number between `-1` and `1`.

Run the code cell below to print some information about the environment.

In [4]:
# reset the environment
env_info = env.reset(train_mode=True)[brain_name]

# number of agents
num_agents = len(env_info.agents)
print('Number of agents:', num_agents)

# size of each action
action_size = brain.vector_action_space_size
print('Size of each action:', action_size)

# examine the state space 
states = env_info.vector_observations
state_size = states.shape[1]
print('There are {} agents. Each observes a state with length: {}'.format(states.shape[0], state_size))
print('The state for the first agent looks like:', states[0])

Number of agents: 20
Size of each action: 4
There are 20 agents. Each observes a state with length: 33
The state for the first agent looks like: [ 0.00000000e+00 -4.00000000e+00  0.00000000e+00  1.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.00000000e+01  0.00000000e+00
  1.00000000e+00 -0.00000000e+00 -0.00000000e+00 -4.37113883e-08
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.75471878e+00 -1.00000000e+00
  5.55726624e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00
 -1.68164849e-01]


### 3. Take Random Actions in the Environment

In the next code cell, you will learn how to use the Python API to control the agent and receive feedback from the environment.

Once this cell is executed, you will watch the agent's performance, if it selects an action at random with each time step.  A window should pop up that allows you to observe the agent, as it moves through the environment.  

Of course, as part of the project, you'll have to change the code so that the agent is able to use its experience to gradually choose better actions when interacting with the environment!

In [5]:
env_info = env.reset(train_mode=False)[brain_name]     # reset the environment    
states = env_info.vector_observations                  # get the current state (for each agent)
scores = np.zeros(num_agents)                          # initialize the score (for each agent)
while True:
    actions = np.random.randn(num_agents, action_size) # select an action (for each agent)
    actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1
    print(actions)
    env_info = env.step(actions)[brain_name]           # send all actions to tne environment
    next_states = env_info.vector_observations         # get next state (for each agent)
    rewards = env_info.rewards                         # get reward (for each agent)
    dones = env_info.local_done                        # see if episode finished
    scores += env_info.rewards                         # update the score (for each agent)
    states = next_states                               # roll over states to next time step
    if np.any(dones):                                  # exit loop if episode finished
        break
print('Total score (averaged over agents) this episode: {}'.format(np.mean(scores)))

[[ 1.         -1.          0.04216295 -1.        ]
 [-0.21321668 -0.0158131  -0.5267069   1.        ]
 [ 0.2007556   0.31234437  0.28688796  0.88198611]
 [ 0.36559495 -0.08891289 -1.         -0.39894143]
 [ 1.          0.9455272  -0.04213323 -0.55593688]
 [-1.          0.68763945 -0.85963489 -0.63260208]
 [ 0.94075537 -1.          1.          0.33107079]
 [ 1.         -1.          0.20278826 -0.87999206]
 [ 1.          0.98462272  0.71932158 -0.09258609]
 [-0.96971811 -0.13769735 -1.         -0.95458416]
 [-0.51974829  0.03027034 -0.76172127 -0.58499444]
 [-0.93916487  0.58190018  0.40318763  1.        ]
 [ 1.         -1.         -0.49481317 -0.48736709]
 [ 0.77558026  1.          1.         -0.23025097]
 [ 0.44555595 -0.70549592  0.34907398 -1.        ]
 [-1.         -1.         -0.54278514 -1.        ]
 [ 1.          0.4872816   1.         -1.        ]
 [ 0.9819204  -0.3106484   0.23067785 -1.        ]
 [-1.          1.          0.54697108  1.        ]
 [-0.12159482  1.          1.  

[[ 1.         -1.         -1.          1.        ]
 [ 0.05522854  1.         -0.37686096  0.25670857]
 [ 0.4768518  -1.          1.          1.        ]
 [-0.45132133  1.          0.10216324  0.44038833]
 [ 0.26413854  1.          0.01070209 -0.66638083]
 [-0.59275748  0.90502769  1.         -0.31860747]
 [-0.30213709 -0.40665284 -0.107981    0.46400737]
 [ 0.68602349 -1.         -1.          0.33447151]
 [-0.83576179  0.22569429  0.03667743 -0.95309677]
 [-0.27640146 -0.60260355  0.55729403  1.        ]
 [-0.14674595 -0.53467581 -0.16639151 -0.02220446]
 [-0.8785685   0.00582355 -0.10973473 -1.        ]
 [ 0.99350565 -0.90103189  1.         -0.12960775]
 [-1.         -1.         -0.2955764   1.        ]
 [ 0.60050932  1.          0.05293244 -0.37197823]
 [-0.60982617 -1.         -0.92219132  0.69229607]
 [-0.79048642  0.23434659  0.97104934  1.        ]
 [-1.         -1.          1.          0.99506537]
 [ 0.29408856  0.84296916 -0.02629593  0.81660501]
 [-1.          1.          1.  

[[-0.26107312 -1.         -0.18382675 -1.        ]
 [ 0.18668449  0.94593602 -1.         -1.        ]
 [-0.9225955  -0.40453801  0.0849043   0.38545135]
 [-0.03163686 -0.01838511  0.39478477 -0.17403288]
 [-0.89270142 -0.33238863  0.61708427 -0.47417818]
 [-1.         -0.77041753 -0.26617002 -1.        ]
 [ 0.94475941 -0.13106139 -0.10142049  0.35686436]
 [-0.54034914 -0.71526765  0.2290894   0.96934951]
 [ 0.46481499 -0.25178324  0.58029496 -0.03524063]
 [-0.19074009  0.47869064 -0.09481277 -1.        ]
 [-1.          1.         -0.26862841  0.35199997]
 [ 0.50693112  0.30198005  0.45575413  0.20996793]
 [ 0.00734537 -0.96704806 -0.61300743 -0.68207217]
 [-0.61318114 -0.11999065  0.7387254   0.71520913]
 [-0.19670286  0.39053495  0.77201655  0.61334299]
 [ 1.         -1.          0.70591084  0.00484052]
 [-0.03491855  0.08889729 -0.08867841  1.        ]
 [-0.92041056  0.49496988 -1.         -1.        ]
 [ 0.41999122  0.22526576 -0.22486649  1.        ]
 [-1.          0.06474989 -0.42

 [-1.00000000e+00 -3.44387041e-01  1.00000000e+00  1.00000000e+00]]
[[-0.65642002  1.          0.62647077  1.        ]
 [ 0.45067925 -1.         -1.          0.2680124 ]
 [-0.34730672 -1.          0.29818201  0.33501014]
 [ 0.00320321 -0.00885922  1.          1.        ]
 [ 0.3160534   0.58447294 -1.         -0.22453306]
 [ 0.71379919 -1.         -0.93939536 -0.43219561]
 [ 0.3081023  -1.         -1.         -0.26623015]
 [ 1.          0.38885975 -1.          1.        ]
 [-1.         -1.          1.          0.24180051]
 [-1.         -0.42637857  0.10951159 -1.        ]
 [-0.06806797 -1.          0.81686144 -0.55461501]
 [-1.         -0.499389   -0.97823706  0.89983366]
 [-1.         -0.87069955 -1.          0.81747475]
 [-0.72698345 -1.         -0.4571523  -1.        ]
 [-1.          0.50551646 -0.75971202 -1.        ]
 [-0.88346728  0.69467462 -0.52169332  0.02856118]
 [ 0.82449885  0.5477037   1.          0.45493331]
 [-0.79308371  0.96852358  0.11424419 -1.        ]
 [-0.88828909 

 [-1.          0.19168722  0.79578604 -0.30062492]]
[[ 1.         -0.0897177  -1.          0.58461226]
 [ 0.2999591  -1.         -1.          0.7420597 ]
 [ 0.40418072  1.          1.          0.95000923]
 [-0.31367265  1.         -1.          0.35591317]
 [ 1.         -1.          0.01825578  1.        ]
 [-0.3508097   0.63751494  0.08255423 -0.80850975]
 [ 0.17303161  0.31071106 -0.17501047  0.54771795]
 [ 1.          0.9222364   0.18037098  0.0346801 ]
 [ 0.66301718  0.81760713 -1.          0.08044223]
 [-0.49401847 -0.05121988 -0.10564024  0.70518436]
 [-0.28711828 -0.76021482  1.         -0.72949339]
 [ 1.         -1.         -1.          0.56780531]
 [-0.58005805 -0.65067095  0.12670272 -0.12567196]
 [-0.35151472 -0.63417018 -0.37703133 -0.58538975]
 [-0.32425322 -0.11566781  0.03500606 -1.        ]
 [ 1.          0.52490855 -0.30655679 -1.        ]
 [ 0.61567069  0.6204747   0.81780122  0.73774108]
 [ 1.          0.48226797  1.         -0.04657649]
 [-0.1081385   0.34967625  1. 

[[-0.68090917  0.40465447  0.95558093 -0.08002286]
 [ 0.43850316  0.3411483  -0.15019185  1.        ]
 [ 0.03409366  0.87080918 -0.10066642  0.61993329]
 [-1.         -0.28364932  0.49515392 -0.70795914]
 [ 0.74927088 -0.71761514  0.42568637 -0.18306257]
 [-0.87134633 -1.          1.         -1.        ]
 [ 0.07130442  0.02541629  0.80639519  0.62088748]
 [-0.36261647 -1.         -0.53446891  1.        ]
 [ 0.79009661  0.26762389 -0.04776971  0.14489767]
 [-0.78617642  1.         -1.         -0.48549471]
 [ 0.36426227 -1.         -0.42092206  0.11090252]
 [ 0.82352423  0.45864711  0.35568735  1.        ]
 [ 0.28070614 -0.01466392 -0.04804095 -0.35884932]
 [-0.32520416 -1.         -0.04873955  0.14734565]
 [ 0.32060028 -0.28116253  0.79786771 -0.44718884]
 [-0.39236916 -0.74404831 -1.          1.        ]
 [-0.05128209  0.23826219  0.13520956 -0.11270618]
 [ 0.05843117 -1.         -1.         -1.        ]
 [ 1.         -0.02055425  0.62672073 -0.13281534]
 [-0.42788908 -1.         -0.01

[[ 6.08719679e-01 -1.00000000e+00 -5.84442320e-01  1.00000000e+00]
 [-1.00000000e+00 -5.72243309e-01  4.85638546e-01  1.00000000e+00]
 [ 7.84623322e-01 -4.28732362e-01  1.00000000e+00  9.75661329e-01]
 [ 4.06687087e-01 -1.00000000e+00  7.04108719e-01  9.68099790e-01]
 [-1.73703935e-01  6.09029882e-01 -1.00000000e+00 -7.92496010e-01]
 [-2.72097993e-01 -1.00000000e+00  1.00000000e+00 -1.07314698e-01]
 [-9.21181083e-01  9.74162607e-01 -6.31473369e-01 -5.89660473e-02]
 [-8.00127786e-01  1.00000000e+00 -7.56712002e-01  6.47122034e-01]
 [-2.87483876e-01 -7.38032461e-01 -4.65966188e-01  3.00667494e-01]
 [-1.00000000e+00  5.49362439e-01  1.09504250e-01  7.54513094e-01]
 [ 8.14386619e-01  9.91305613e-01 -5.02379438e-01  5.61464418e-01]
 [-1.00000000e+00  1.70360266e-01  7.53960825e-01 -7.09629243e-01]
 [-9.78063050e-01  8.04745928e-01  1.00000000e+00 -8.30316995e-01]
 [-1.00000000e+00  1.00000000e+00  1.00000000e+00 -3.18483019e-04]
 [ 1.00000000e+00 -2.71537970e-01  5.89217688e-03  7.15296004e

[[ 0.42771406 -1.         -1.          0.25996554]
 [ 0.02653964 -0.72189467  0.07173074 -0.19127302]
 [-1.          0.32965129  0.38433721  0.8181996 ]
 [-0.15428046 -1.         -1.          0.32983774]
 [ 0.09627313  0.08329261  1.          0.19956662]
 [ 0.85822383 -0.68416848  0.73790498  0.87215072]
 [ 1.         -0.57018704 -0.55338727  1.        ]
 [ 1.         -0.30567883  0.13234072 -0.23358092]
 [ 0.64229426  0.24714122 -0.21826935 -1.        ]
 [-0.68569743 -0.6649481   1.         -0.71100997]
 [-1.          1.         -1.         -0.4273425 ]
 [ 0.27563124  0.25093456 -1.         -0.46270208]
 [ 0.18968798 -0.08789478  0.38260962 -1.        ]
 [ 0.92326877 -0.9423272  -1.          0.14457108]
 [ 0.42198272  0.46482204  1.          0.9790765 ]
 [-0.66368345 -1.         -0.45878853  1.        ]
 [ 1.         -0.85625058  0.03676974  1.        ]
 [-1.          0.21264509 -1.          1.        ]
 [ 0.33217384 -0.4037517   1.         -0.60111732]
 [-1.          0.85369193  0.63

[[-1.          0.44831249  0.47838122 -0.58164139]
 [-0.28902262 -0.25114322  0.09051971 -0.24130863]
 [ 1.          1.          0.68541069  0.33406451]
 [ 0.20143198  0.27820377 -0.41186578  0.2890087 ]
 [ 0.49382145 -1.         -0.10897472 -0.61542718]
 [-0.8666679   0.74801443  0.67881584  0.72121278]
 [ 0.66430855  0.46782968  1.         -0.92951302]
 [-1.         -0.35985003  1.         -1.        ]
 [ 0.12343043 -0.50680748 -0.24983737  0.55912246]
 [ 1.          0.33200047 -0.12821934  1.        ]
 [ 0.24422504  0.7348122   0.75265712 -0.08182211]
 [-1.          0.35314025  0.61952559 -1.        ]
 [ 0.89784281 -0.04665871  0.24549626  0.7631896 ]
 [ 0.86663071  1.         -0.0109282  -0.47084402]
 [ 1.          0.79993915 -0.08026672  0.35595819]
 [-0.75255631  0.01394535 -0.87106249 -1.        ]
 [-0.28494899  1.         -0.91394989  1.        ]
 [-1.         -1.         -0.19041856  0.79545614]
 [ 0.76903     0.91942854  0.48705213  0.81073666]
 [-0.12240184  0.63738577 -0.00

[[-1.          0.51317015  0.88337973 -0.6466504 ]
 [-0.60460548  1.          0.72941221 -0.31488509]
 [ 0.43325233  0.15686154  1.         -1.        ]
 [ 1.         -0.9953573  -0.32852195  0.1565352 ]
 [-1.         -1.         -0.88454888  0.17113078]
 [-0.67399059  0.09856457  0.42786827 -0.60465394]
 [ 0.07550622 -0.17677875 -0.67030387  1.        ]
 [ 0.95265371  0.88505616 -0.47264426  0.87411973]
 [-0.00261681 -0.51399245  1.         -0.9971934 ]
 [ 0.96666808  0.86043296  0.75999172 -0.52249415]
 [-0.74708701 -0.84272283  0.68311929 -0.40000193]
 [ 0.15164323 -1.         -0.33107915 -0.67790445]
 [ 0.15210366  0.42626169 -0.27149582  0.06850947]
 [-0.13165105 -0.21311667  1.          0.93903164]
 [ 0.08063407 -0.58541493  0.82871071 -0.34365587]
 [-0.50719079  0.7652142   0.17330295 -1.        ]
 [-1.         -0.22642431  0.50313796 -0.41731387]
 [ 0.32262783  0.02912031  0.40557028  0.90471446]
 [-0.11456276  0.41250246  0.63603329  0.11206637]
 [ 1.          0.12112334 -0.96

[[ 1.          0.15557016  0.6029359   0.50370901]
 [-0.22165584  0.44603748 -0.59526588  1.        ]
 [ 1.         -0.05047188 -0.77588054  0.59440969]
 [ 1.         -0.56391174 -1.         -1.        ]
 [ 1.         -0.78646967  1.          0.75022939]
 [-1.          0.83536305 -1.          0.37170367]
 [-0.09843862 -0.14790094 -1.          1.        ]
 [ 1.         -1.          0.74419288  0.17023514]
 [-0.37064607 -1.          0.3020648  -0.08261115]
 [ 0.98533875  0.03090868 -1.         -1.        ]
 [-0.0316076  -1.          0.40197991  0.07317266]
 [ 0.33399726 -0.01712604  0.5216883  -1.        ]
 [-1.          0.01560765  0.05835631 -0.28742852]
 [ 0.06632071 -0.27880555 -1.         -0.11954225]
 [-0.05678497  0.78699308 -0.09483141  0.63822585]
 [-0.0684976   0.75386796  0.89873106 -0.29223399]
 [-0.10882433  0.4743225  -1.         -0.19792075]
 [-0.42361574 -1.          0.60198161  0.71685948]
 [ 1.          1.         -1.          0.56093031]
 [ 0.3952804   0.1555045   1.  

 [-5.22726343e-01 -1.00000000e+00 -7.08050259e-01  5.83483884e-02]]
[[-0.47184983 -0.66216294 -0.24303472 -0.65275179]
 [-0.3594068   0.4229459   0.73956006  0.45789919]
 [-0.81137094  0.19687685  0.62648086  0.4896688 ]
 [ 0.53153046  1.         -1.          0.60551314]
 [ 0.37246076  0.2594034   1.          0.39645307]
 [ 0.87608127 -0.39167379 -1.         -0.76811276]
 [ 0.30611964 -0.12432879  0.37763906  0.04005448]
 [ 0.41669623 -1.         -0.40851205  0.54003888]
 [-0.31218755 -0.3048363   0.21094676 -1.        ]
 [ 0.1417931  -0.05613872 -0.23215431 -0.54892543]
 [-0.82714805  0.59381508  0.98208002 -0.23157623]
 [ 0.61136887  1.         -1.          0.20069381]
 [-0.76252432  1.          0.54624922 -0.4362257 ]
 [ 1.          0.50909739  1.         -0.28293509]
 [-0.34689764 -0.69202492  1.         -0.3733278 ]
 [ 0.66463047  1.          1.         -1.        ]
 [ 0.2508168  -0.30663564 -0.85637982  0.16806319]
 [ 1.          0.88804478  1.          0.18371956]
 [-0.69979114 

[[-1.          0.62763726 -1.         -0.9693107 ]
 [-0.4375221  -0.96565023 -0.98294413  0.31299167]
 [-1.          1.          1.         -0.32691717]
 [-0.55076449 -0.42214351  0.18480393  1.        ]
 [-1.         -1.         -1.         -1.        ]
 [ 1.          1.          0.57540208  0.23999141]
 [ 1.          1.          0.74329432 -1.        ]
 [ 1.          1.         -0.42509813 -0.12005354]
 [-1.         -0.57480535 -1.         -0.42509939]
 [-1.          0.43191083 -0.93628973  0.94190975]
 [ 0.56155283  0.17603955 -0.77981238 -0.63305974]
 [-0.10242066 -0.19415588  0.33729793  1.        ]
 [ 1.         -1.          1.          1.        ]
 [-0.73060356 -0.67829314 -0.91157316  0.17041682]
 [-0.34261001  0.58829548 -0.23989961  0.99538168]
 [-1.         -0.37461263 -0.88438256 -0.52084971]
 [ 0.05181161  0.58575667  0.08050068 -0.50978253]
 [-0.55881794 -1.          1.          1.        ]
 [-1.         -0.49611679 -0.71227821 -0.09768642]
 [-1.          0.0813511   0.05

[[-1.00000000e+00 -1.00000000e+00 -7.18073360e-01 -1.62042674e-01]
 [ 1.00000000e+00  3.57237896e-01 -9.75795111e-01  1.00000000e+00]
 [-1.00000000e+00 -8.91953503e-01  3.36308979e-01 -9.77615808e-01]
 [ 7.82895749e-01 -1.00000000e+00  7.77115968e-01  1.00000000e+00]
 [-7.99094426e-01  1.00000000e+00 -6.99976083e-01 -1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00 -1.00000000e+00 -5.54828407e-01]
 [ 1.00000000e+00 -1.00000000e+00  2.00042827e-01  5.89406072e-01]
 [ 9.51446024e-01 -5.61251032e-01  1.00000000e+00  9.74643039e-01]
 [-3.50832444e-01 -1.48201153e-01 -6.17187363e-01 -8.82803339e-04]
 [-2.11292226e-01  4.83394961e-01  9.56869598e-01  5.01700722e-01]
 [ 1.00000000e+00  3.41344163e-01  8.21572360e-01 -1.00000000e+00]
 [-1.00000000e+00  8.09892963e-02 -8.96793919e-02 -1.00000000e+00]
 [-8.95823127e-01 -1.00000000e+00  7.68685942e-02 -5.88905852e-01]
 [ 1.00000000e+00  9.01267966e-01 -1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -1.00000000e+00 -7.13644017e-01  2.64732393e

[[-0.35728867  1.         -0.24451711  0.77712628]
 [ 0.36959054 -1.         -1.          0.01143885]
 [ 0.41534401 -1.         -0.06583673  0.70651707]
 [ 0.08476056 -0.49537737 -1.          0.55009952]
 [ 0.54777358 -1.         -0.18651825  0.72839204]
 [-0.7501904  -1.         -0.3678329   0.21524242]
 [-0.13985797  0.43032784 -0.51898598 -1.        ]
 [-0.21314077  1.         -0.01945026 -0.3634052 ]
 [ 0.63829397  1.         -1.          0.69862337]
 [-1.          1.         -0.75524618 -1.        ]
 [-0.51200178 -0.68211635 -0.57640054  0.81401177]
 [ 0.84650708  0.89659515  0.41298497 -0.3960436 ]
 [ 0.1735237   0.00184169  1.         -0.5379797 ]
 [ 1.         -0.30615679 -1.          0.97078856]
 [-0.4828961   1.          1.         -0.31142697]
 [-0.99122656  0.76831872  0.10132439  0.7192755 ]
 [-0.04013789 -0.35003219  0.79871692  0.12578247]
 [ 1.         -0.8291882   0.29666469 -0.96031663]
 [-0.80427901 -0.59791937 -0.50176086  0.71324229]
 [ 0.49580592 -1.          0.41

 [-0.55687405  0.61612889  0.81385512  0.91959166]]
[[ 0.33778249 -0.36671866  0.72538056 -0.34823922]
 [ 0.42398314  1.         -0.34124888 -0.11701   ]
 [ 0.1939735   0.01552691  0.32889843 -1.        ]
 [ 1.          0.75113338  0.19655615 -0.62743479]
 [-0.80019981 -1.         -0.80559784  0.51063841]
 [-0.99123625 -0.05563251 -0.2705352  -1.        ]
 [ 1.         -0.5532595  -0.56181153  0.49911477]
 [ 0.27535162  0.27302138  0.60647723  0.73812881]
 [ 0.62844654  0.11681656 -1.          0.15166711]
 [ 0.34847936 -0.17881883 -0.97137854 -1.        ]
 [ 0.27637443  1.          0.43437927  0.79006606]
 [-0.83011367  0.55215702  0.24610803 -0.03001868]
 [ 1.         -1.         -1.         -0.4453819 ]
 [-1.          0.54619679  0.33621974  0.37653555]
 [ 1.          1.          0.06265181 -0.01596465]
 [-0.65607968  0.46650074  0.31271947 -0.93766978]
 [-1.          0.52993948  0.37084089  1.        ]
 [ 0.35425853  0.03742118 -0.41324454  0.79655966]
 [-0.70578442 -0.14654036 -0.5

 [ 0.4621396  -0.76113567  0.14123031 -1.        ]]
[[ 0.4814088   1.         -1.          0.46744078]
 [ 0.37021602  0.19833291 -0.94518685  0.00808606]
 [-0.67753722  0.73846895 -0.47841156  1.        ]
 [-0.40989497 -1.          1.         -0.00287504]
 [-0.53401102  1.         -0.2151831   0.50655746]
 [-0.5394192  -1.          1.          0.01136537]
 [-0.50708367 -1.         -1.          1.        ]
 [-0.44350275  1.          1.          0.84883033]
 [ 1.         -0.85493953 -1.          0.26435405]
 [ 1.          0.65471883  0.46114072  1.        ]
 [ 0.74718224 -0.65630382 -1.         -0.65423423]
 [ 0.48059864 -1.         -1.          0.4807435 ]
 [ 1.          0.11016872 -0.06386606 -0.58077464]
 [ 0.90721166  0.24839536  1.          0.51122283]
 [-0.63470675 -1.         -1.          0.1089785 ]
 [ 0.62196309 -0.21102785 -0.30937414  1.        ]
 [-0.36597822 -1.          0.09570533 -0.6918259 ]
 [ 0.38910012  0.53909781  0.55240578  1.        ]
 [-1.          0.21731788  0.6

 [ 9.59997120e-02 -1.00000000e+00  4.65021582e-01  2.72391045e-01]]
[[ 0.04845726 -1.          0.53078477  0.48599027]
 [-1.         -0.45940406  0.46790619  1.        ]
 [ 0.83334367 -1.          0.18611363  0.99083078]
 [-1.         -0.00325397 -0.26400178  0.64711205]
 [-0.41593078 -1.          1.         -0.8272384 ]
 [-0.06173018 -0.49979977  1.          0.65122425]
 [ 0.34541447  0.11701914  1.         -0.71359963]
 [-0.55424031  1.          0.55290898 -0.33041638]
 [ 1.         -1.          0.2350347   0.99994488]
 [ 0.66682411 -0.78696857  0.32375258  0.19804982]
 [ 0.28120321 -0.3260261  -0.75152879  0.68759638]
 [ 0.22007578  0.56385525 -1.         -0.21321733]
 [-0.40603408  0.95387612 -1.          1.        ]
 [-0.23138334 -0.85863938  0.04694352  0.60536252]
 [ 0.02181322  0.25822743 -0.27928186 -0.37530983]
 [ 1.         -1.         -0.72587853  0.70295337]
 [-0.61943834  0.99655348  0.95104675 -0.77354977]
 [-0.36582783  1.         -0.89084148  0.99889129]
 [ 0.83083641 

 [-0.14972717 -0.80732154  0.16656211  0.02915914]]
[[-0.17400845  1.          0.55455785  0.0509708 ]
 [-0.97977148  1.         -1.         -0.22764876]
 [ 0.73073079 -0.8628102  -0.95293148 -0.69496848]
 [ 1.         -1.          1.         -0.34365208]
 [-1.         -0.19349187 -0.33298569  0.07290744]
 [-0.76064059 -1.          1.         -1.        ]
 [-0.90447765  0.19852574  0.14940464 -0.43029034]
 [ 1.         -0.69527039 -0.52161913  0.82004275]
 [ 0.10781002  0.03876577  0.73347629 -0.7325838 ]
 [-0.2327511   0.71259733  0.14545812 -0.40518115]
 [ 0.49292735 -0.03536855  0.53161198 -1.        ]
 [-0.01464641  0.31440354  0.3422483   1.        ]
 [ 0.34751936  0.16373479 -0.36910666  1.        ]
 [-1.         -1.         -1.         -0.47155158]
 [-1.         -1.          0.48868344  1.        ]
 [-0.18416388  1.          0.14410634  0.91211962]
 [ 0.2700548  -0.56077384  0.45740592 -1.        ]
 [ 0.9893765  -0.64729574  1.          0.35263523]
 [-1.          1.          0.7

[[-0.06412034 -0.13318421  0.57437962 -0.43868523]
 [-0.63545495  1.         -1.         -1.        ]
 [ 1.         -1.          1.         -0.40457035]
 [-1.          0.14205538 -0.39485799 -0.6986476 ]
 [ 0.94963313  1.          1.         -0.03984155]
 [ 0.18850181  1.          0.04165945 -0.2202721 ]
 [ 0.05375707  0.93440287 -0.56284261 -0.26486524]
 [ 0.25688456  1.         -1.         -1.        ]
 [ 0.18057569 -0.0624703  -1.         -0.40444722]
 [ 1.          1.          1.          0.76285503]
 [ 0.18473297  0.42676546  1.         -0.91692606]
 [-0.2390523  -0.55364725 -0.46304066  1.        ]
 [-0.99128827 -0.18737847 -0.68965186 -0.46926677]
 [ 0.78222366  0.26986313  1.          0.57163404]
 [-1.         -0.90203997 -0.35773532  1.        ]
 [-0.76212152  1.          0.57866833 -1.        ]
 [-0.81167611  0.86829046 -0.94113372 -1.        ]
 [-0.65967859  0.86907115  0.34912197  1.        ]
 [-1.          1.         -0.57992646  1.        ]
 [-0.01810581 -0.18742397 -1.  

 [-1.         -0.07327994  0.42258379 -1.        ]]
[[-1.          0.58640159 -1.          0.5984812 ]
 [-0.28611994  0.38983902 -0.02260204  0.49202517]
 [ 1.         -0.83438191  0.44085906 -0.72190573]
 [ 0.07132828  1.          0.17661948  0.09370303]
 [-0.3644692  -0.06149004  1.          0.82503523]
 [-1.          0.35458722 -0.95578597 -0.07161565]
 [-1.          0.85654053 -0.50136952  0.74632519]
 [-1.          0.30975447 -0.56346068  0.93226215]
 [-0.96443133 -0.1074886  -1.         -0.64705286]
 [-0.44676767 -0.57790016 -0.94521045 -1.        ]
 [-1.          0.67373395 -1.          0.69084554]
 [-0.10553494  0.71906206 -0.26636404  0.39097652]
 [-0.58810307 -0.39183023  0.34181801  0.02544031]
 [ 1.          0.75307031 -0.38967467 -0.82648622]
 [ 1.          0.36354744  0.52397383  0.2242651 ]
 [ 0.0323242  -0.09267821 -1.         -0.74530976]
 [-0.45985138  0.38711063  1.          0.97147825]
 [ 0.9453948  -0.05079472  0.80506236 -0.17971434]
 [ 0.96985777 -0.13137467 -0.4

 [-0.58096748  0.19613055  1.          0.17314928]]
[[ 0.02438997  0.46910001 -0.8655101   1.        ]
 [-0.66395269 -0.94567543 -0.3214101  -0.89900195]
 [-1.          0.85116935  0.03228869  1.        ]
 [-0.7321819  -0.39154836 -1.          0.44581424]
 [-0.09949047 -1.         -0.0431954   0.176788  ]
 [ 0.25075707 -0.77738051  0.03775873 -1.        ]
 [-0.6503658   0.37998445 -1.          0.78495635]
 [ 1.         -1.          0.62308702 -0.25319552]
 [ 1.         -0.03803318  0.2780544   0.07727923]
 [-1.         -1.          0.5059376  -1.        ]
 [ 0.9528073  -0.37894619  0.96346458 -0.42978048]
 [-0.3835995  -0.16845716 -0.43850185  1.        ]
 [-1.         -0.60026802 -0.84513033 -0.43959009]
 [ 0.91040072 -1.         -0.22326771 -1.        ]
 [-0.08199006  0.03536752  0.73485218  0.68650534]
 [ 0.09139942  0.2209637   0.6277709  -0.31820748]
 [-0.29189276 -0.20863202 -0.40151774  1.        ]
 [-0.77637042  0.44739094 -0.5907878   1.        ]
 [-1.         -0.59037048  0.1

[[-1.          0.14139042 -0.08974356  0.14041736]
 [-1.         -0.08051391 -0.62301491 -1.        ]
 [-0.45625622 -0.83559936 -0.68069543 -1.        ]
 [-0.239821    1.         -1.          0.84228973]
 [ 0.96152733 -0.69854951 -0.90809379  0.37025126]
 [ 0.88162254  1.         -0.46257347 -0.38391227]
 [ 0.94109186 -0.62788976  0.13342589  0.40889396]
 [ 0.13889206 -0.16713125  1.          0.90603401]
 [ 0.50778668 -0.84529606 -0.27580297 -0.71978266]
 [ 0.39454177  0.85358192 -0.87655349 -1.        ]
 [-0.68313441  0.03523969  0.23943813  0.43198154]
 [ 0.4629883   0.34592689 -0.92012515  0.16781934]
 [-1.         -0.11172427 -0.26914515  0.08909273]
 [-1.          0.28418196 -1.          1.        ]
 [ 0.52370857  0.14960921  0.82757802  0.08230849]
 [-0.51085661  0.10461604  1.          0.02505434]
 [ 1.          0.25519449  0.61012475 -1.        ]
 [ 0.68371154 -0.36925946 -1.          1.        ]
 [ 0.59630375  0.20042393  0.74798696 -1.        ]
 [-0.38715143  1.         -0.37

[[-0.01246972 -0.17352195 -0.32508011  1.        ]
 [ 0.66803361  1.         -0.27452573 -0.41800753]
 [-0.74383988 -0.20565111  0.01150486 -0.00489749]
 [-1.         -0.23462147  0.93439576 -1.        ]
 [-1.          0.29281538  1.          0.10723768]
 [-0.59089582 -1.         -1.          0.45973036]
 [-0.70343511 -1.         -1.          0.00853559]
 [-0.02883615 -0.5419156   0.17560975  0.57888014]
 [-0.56141451 -1.         -1.          0.07971042]
 [ 0.46154487 -1.         -0.71872094 -0.66068779]
 [-1.          1.          0.02253828  0.86542281]
 [-0.24320754  0.09532713 -1.          0.52333693]
 [ 1.         -1.         -0.05295656 -1.        ]
 [-0.11364825  1.         -0.56283058 -0.32287019]
 [-0.85769406  1.          0.26369733  0.06303614]
 [ 1.          0.18677193 -1.         -0.83913767]
 [-0.88206477 -0.10721089 -0.30369108  0.05132236]
 [-0.23251678 -0.57405527 -1.          1.        ]
 [ 1.          0.14317251  0.11186683 -0.1653998 ]
 [-1.          0.82087068 -0.87

[[-1.         -1.         -0.01700936 -0.02800598]
 [-0.24944369  1.          1.          0.75692976]
 [ 0.64598142 -0.27633985  0.36876975  1.        ]
 [ 1.         -1.          0.68874939  0.91442428]
 [ 1.         -1.          1.         -1.        ]
 [-1.          0.71652363  0.66898589 -1.        ]
 [ 1.          0.28528819  0.12806782  0.58627503]
 [-0.66986155 -0.5367432   0.63566952 -1.        ]
 [-0.45100166 -0.57784897 -0.58567168  1.        ]
 [-0.10023628 -0.47899794  0.1479405  -1.        ]
 [ 0.66576116  0.07022813  0.29035238  0.76279209]
 [-0.37116208  0.25135263 -0.4656423  -1.        ]
 [-0.45973531  1.         -0.74939408  0.07354385]
 [-0.77017586  0.98099697 -1.          0.42996004]
 [ 0.52747897  1.          1.         -0.79099225]
 [-0.76824133  0.85996209  0.88490827  0.12814275]
 [ 0.77917718  0.04301181 -0.06002059 -0.32867622]
 [ 0.29565585  0.28116851 -0.49072724  1.        ]
 [-0.72658228  0.58684143 -0.57247312 -1.        ]
 [ 0.23620214  0.39010783 -1.  

[[ 1.          0.09477055 -0.26241581 -0.35494404]
 [ 0.66726951 -1.          0.49642399 -0.06988807]
 [-0.88868123  0.15626134  0.38377626 -0.49977497]
 [ 1.         -0.63363046  1.          0.6076563 ]
 [-1.          0.23406726  0.11707952 -0.06990296]
 [-0.32371432 -1.          0.18594415 -0.34267628]
 [ 0.22762006 -1.          0.66977035 -0.99743544]
 [-0.54325869  0.13196797 -1.         -1.        ]
 [ 0.50518402 -0.36395158  0.50506449  0.85561306]
 [ 0.05189025  0.95547839 -1.          0.62839811]
 [ 0.85580173 -0.45190924 -0.60822662  0.41939628]
 [-0.57566142 -1.         -1.          0.53121473]
 [-0.72322088 -0.63531336  0.15711439  0.89791757]
 [-1.          0.58956517 -0.57446023  0.28829856]
 [ 1.         -0.65938871  0.95489753 -0.46339741]
 [ 0.32529588 -1.          1.         -0.2978386 ]
 [-0.65939991  0.9379365   0.00768708 -0.06513435]
 [-1.          0.68035843 -0.51596221  0.12660736]
 [-0.33575403  1.         -0.98401943 -0.39203132]
 [ 0.06186949  0.45395203 -1.  

[[-0.02054808  1.         -1.          0.28737622]
 [ 1.         -1.          0.21590564  0.14855385]
 [-0.29187408  1.          1.          1.        ]
 [-0.29427977  0.25598049 -0.00552085 -0.52168785]
 [ 0.06660253  0.05320659 -0.31480677  1.        ]
 [-0.01148056  0.11295009  0.50145659  0.10268097]
 [-1.         -1.         -0.72176781 -1.        ]
 [ 0.13097194  0.86260657 -0.24532544  0.5276633 ]
 [ 0.16416691 -0.23191037 -0.09159232 -0.65262363]
 [-0.07139176 -1.          0.65557959  0.56770145]
 [ 1.          0.19356108  0.87283042 -0.68849397]
 [ 1.         -1.         -0.67907824 -1.        ]
 [-0.61505504 -0.425593   -1.          0.26979659]
 [ 0.15472348 -0.5312652  -0.943224    0.15071763]
 [ 1.         -0.2040102   0.71708587  0.11499652]
 [-0.27231295 -0.17058261 -0.6004993   0.29409416]
 [-0.60672909  0.15456968 -1.         -0.81402689]
 [-0.69987066 -1.         -0.47196378 -1.        ]
 [ 0.49758581  0.19699449 -0.78698283  0.82049967]
 [ 1.         -1.          0.50

[[-0.98862247  0.7529914  -0.10068911 -0.44335096]
 [-0.15918551 -1.          1.          0.4674742 ]
 [-0.77114331 -0.3806779  -1.          0.47131749]
 [-1.          0.60339681  1.          0.83425789]
 [-1.          1.         -0.44489632  0.51330544]
 [ 1.          0.48851394  0.37546839  0.83837037]
 [ 0.16833963  0.19158361 -1.          1.        ]
 [-0.23380233  1.         -0.54991512 -0.94814612]
 [-0.07857608 -0.38645403 -1.         -0.07673671]
 [ 1.          1.         -1.         -0.7248295 ]
 [-0.56067989  1.          0.05309312  1.        ]
 [-0.5994676   0.17857103 -0.51199569  0.12363411]
 [-1.          0.11382611 -0.76562865 -1.        ]
 [-0.67396677 -0.45345556 -0.08749959  0.08477625]
 [-0.56320907 -1.          0.76094579 -0.01342374]
 [ 0.95781998 -0.98920662 -1.         -0.14305284]
 [-0.81421742 -0.84761074  0.85335804 -0.56088373]
 [-0.49491159 -0.62156293 -0.61883201  1.        ]
 [ 0.68079971  1.          0.34438147  1.        ]
 [-0.1209729   0.97279931 -0.83

[[ 0.32082644 -1.          0.58696719  1.        ]
 [ 0.3853174   1.          1.         -1.        ]
 [-0.34575996 -0.85101476  0.04222632  0.23847666]
 [-0.94299732  1.         -0.43064888  1.        ]
 [-1.          1.          1.          0.57816096]
 [ 0.43105471  0.79816825 -0.21559845  0.66436498]
 [ 0.16439101 -0.28843387 -0.30312543  0.56862351]
 [-0.91624961  1.         -1.         -1.        ]
 [-0.03792672 -1.         -0.39692176  1.        ]
 [ 0.95540992 -1.         -1.          0.66944106]
 [ 0.72068477  0.41105912 -1.         -1.        ]
 [ 0.17161428 -0.37667825 -0.08260658  1.        ]
 [-0.17351394  0.29541478 -0.32602281  1.        ]
 [-1.         -0.49349035 -0.79612172 -0.34674245]
 [-1.          1.         -1.          0.14244109]
 [ 0.99300701 -0.70546442 -0.79591608 -0.08056143]
 [-0.41451412  0.13966949  0.62283585  0.62478084]
 [ 0.03719917  1.         -0.08007731 -0.46294878]
 [ 0.26148638 -0.61333969  1.          0.62893873]
 [ 0.05693747  0.11651188  1.  

[[ 0.01047332  0.55040005 -0.48105043  0.17286228]
 [ 1.          0.16285702 -1.         -0.00147598]
 [-0.51635579  1.         -1.          1.        ]
 [-1.          0.65165901 -0.15936857  0.92394936]
 [ 0.42114098  1.          0.84481239 -0.00804959]
 [ 1.          0.05792533 -1.          0.19717804]
 [ 0.35400502 -0.64242397 -0.41116156  0.01476078]
 [-1.          0.35116862 -0.34720695  1.        ]
 [-0.3416872  -1.          0.20312217  0.07555496]
 [ 0.01877416 -0.52262271 -0.23363391  0.08777134]
 [ 0.1118466   0.51132333  0.60525881  1.        ]
 [-0.79791945 -0.65759443  0.59356267  0.36689545]
 [-0.10921235  0.32526615 -1.         -1.        ]
 [ 0.08183587 -0.27279036  1.         -0.11491755]
 [ 0.05689536  1.         -1.         -0.91634393]
 [ 0.90364013 -1.          1.          1.        ]
 [-1.          1.          0.08966977  1.        ]
 [ 1.         -1.         -0.3616781  -0.48019288]
 [-1.         -0.28009773  0.35983461 -1.        ]
 [-1.          1.          1.  

[[ 0.82184371  1.          0.93819982  0.49555282]
 [-0.19217409  0.33133249 -0.7853205   0.54206597]
 [-0.85329434 -0.67407337 -0.22641885  0.43515522]
 [ 1.          0.23970209 -0.58872835 -1.        ]
 [-0.77080132  0.12275633  1.         -1.        ]
 [-0.31424678 -1.         -0.39611086 -0.06328736]
 [-0.60613342 -0.36636923  0.22256693 -0.82675747]
 [-0.4558437   1.         -0.87163811  1.        ]
 [-0.37862822  0.96552956 -1.          0.25760161]
 [ 1.         -0.02867507  0.71897554  0.74013699]
 [-1.          1.         -0.4196177  -1.        ]
 [-0.17799186  0.29690526  0.94170513  1.        ]
 [-0.83776861  1.          0.5550737  -0.40704689]
 [ 0.34151979 -0.32700149  0.80985475  0.40951953]
 [ 0.3978749  -0.82822006 -0.89121102 -0.91993526]
 [ 0.08423769  0.08420024 -0.47192926 -1.        ]
 [ 0.62651087  0.6336079   0.30299222 -0.65263354]
 [ 0.99149513 -0.58755706  0.11341843 -0.34142208]
 [-1.         -0.90510807 -0.40983059  0.41619442]
 [ 0.85908939  0.33904588 -1.  

[[-1.         -0.68132026 -0.12539538 -0.3878899 ]
 [-1.          0.16053095 -0.30347042  1.        ]
 [ 1.          0.43209026 -0.26869471 -0.00838029]
 [-0.4573998  -0.01469476  1.          0.75880596]
 [-0.54439506  0.6675377  -0.49563267  1.        ]
 [ 0.04700028  0.27027282  0.18604707  1.        ]
 [-0.55135275  0.25561636  1.         -0.6837948 ]
 [ 0.58812093 -1.         -1.         -0.87351584]
 [ 0.38043331  0.05104815 -0.04948347 -0.17489444]
 [ 0.52058974 -0.0202238  -0.0392372  -1.        ]
 [-0.39736845  1.          0.66346017 -0.1236757 ]
 [ 1.         -1.         -0.50570222 -1.        ]
 [ 0.22270245  0.48390003  0.95960948  0.05419982]
 [-1.          0.60299199  1.         -0.33207153]
 [-0.32953669 -0.77883392 -0.40599407  0.49508118]
 [ 0.71476764  0.5173888   1.          0.06387047]
 [-0.0864076  -0.29974046  0.03694528  1.        ]
 [-0.79786277 -0.4311666   1.         -0.8094595 ]
 [-0.33322974  0.40657846 -1.         -0.71695519]
 [ 0.85678096 -1.          1.  

[[ 0.1517686  -0.14986951 -1.         -0.51430642]
 [ 1.          0.49660789  1.         -0.43619363]
 [ 0.76985915  0.41450791  0.68345369  0.63328674]
 [ 1.          1.          0.14928391 -1.        ]
 [-0.38331229  0.27830037 -0.15032255 -1.        ]
 [-0.12920365 -0.62323263  0.70307162  0.14605381]
 [ 0.8452119   0.17220342 -0.80198674 -1.        ]
 [ 0.90001312 -0.78753517 -0.98372306  0.21572621]
 [-0.73914877 -0.0232346   0.44307408 -0.86495961]
 [ 0.53052131 -0.2156058  -1.         -0.6196328 ]
 [-1.          0.51997137  0.1412196  -0.34541327]
 [-0.75635013  0.08869028 -1.         -0.00515301]
 [-0.88464155 -0.70539539 -0.47694698  0.00697184]
 [-0.98826071  0.01174586 -1.          0.07633747]
 [ 0.14349577  1.         -1.          0.33404981]
 [-1.          0.53313986  0.53942502 -0.33131885]
 [ 0.53876153 -0.48010753  0.90476767  0.47493228]
 [ 0.19371726  0.03382863 -1.         -0.12924278]
 [-1.         -0.32447065 -1.         -0.23875386]
 [ 1.         -0.08521529 -0.66

[[ 1.         -1.         -0.46621399  0.00483386]
 [-0.75789863 -0.05716442  0.05983506 -0.74253636]
 [-0.43916691  0.56544267  0.87192625  0.23462289]
 [-0.79395552 -1.          0.91092761 -0.20800224]
 [-0.91919067 -0.54559277  0.56249198 -1.        ]
 [-0.33246225 -0.3949011  -1.         -0.71783859]
 [ 1.         -0.36738929 -0.27910924  0.53484918]
 [ 0.67729327 -1.          0.27760161 -0.74332943]
 [ 0.73207713 -1.          0.14411968  1.        ]
 [-0.35770364 -0.70315742  0.63260176 -0.37609898]
 [-0.23915918  0.74968717 -0.02126306  0.48265243]
 [-0.1765545   1.          0.60188919 -0.33772117]
 [ 1.          0.08319992 -0.62070521 -0.82250021]
 [ 0.13711205 -0.26259741 -0.72847738 -0.41370435]
 [-0.51444081  0.25168046  1.          0.33728267]
 [-1.         -0.60802288  0.5095255  -0.58645294]
 [ 1.         -0.88095372  1.         -1.        ]
 [-1.         -1.         -0.71381385  0.04113776]
 [-1.         -1.         -0.11926809 -1.        ]
 [-0.23366898  1.         -0.88

[[ 1.          0.71086869 -0.73359403  0.34600338]
 [-0.23488247  0.9432355  -0.80113958  1.        ]
 [-0.41892012 -0.63702861  0.751279    1.        ]
 [-1.         -0.65692597 -0.74278192  1.        ]
 [-0.67058294 -0.69414449 -0.28685144  1.        ]
 [-1.          1.         -1.          1.        ]
 [ 0.41616748  1.         -0.78354895 -0.9492653 ]
 [ 1.         -0.10290558 -1.          0.98181379]
 [ 0.04637479 -0.31273702 -0.85496943 -1.        ]
 [ 0.749398   -0.38022882 -0.43035046 -0.8366486 ]
 [ 0.62693696 -0.3950788  -0.33511892  1.        ]
 [ 1.          0.13372163  0.12491194  0.85752631]
 [-0.46340275 -1.          1.         -1.        ]
 [ 1.          0.47097864  0.25623189  0.86495731]
 [ 0.72409413 -0.53223998 -0.7017954   0.89592814]
 [ 0.04480443  0.09529912  0.0131106  -0.01544298]
 [ 1.          0.12023306 -1.         -0.44003103]
 [ 1.          0.18555558  0.73359962  0.16075518]
 [ 0.49401349  0.51016208  0.55330059  0.05178484]
 [ 0.77125233 -0.15940184 -0.83

[[-1.         -1.          1.          1.        ]
 [-0.42790388 -0.02259898  1.          1.        ]
 [ 0.66272806 -0.27985213  0.55352467  1.        ]
 [-0.21901935 -1.          0.38779154 -0.92500009]
 [ 0.2774119  -0.64523505  0.23624844 -0.5801759 ]
 [ 0.18561475 -1.         -1.         -1.        ]
 [-1.          0.50155608  0.97427395 -1.        ]
 [-0.59235815 -0.52360993  0.0627826   1.        ]
 [ 1.          0.4492016   0.83945421 -0.46434769]
 [-0.11691631  0.81351875 -1.          0.25692014]
 [ 1.          1.          1.         -0.6680732 ]
 [ 1.         -0.71142079  0.159426    0.33007584]
 [ 1.         -0.6366177   0.41966262  0.99405313]
 [ 0.30238236  0.21280203  1.         -0.07787387]
 [ 0.75800556  0.75804762 -0.07016824  1.        ]
 [-0.44119058  0.88912369 -0.68487537 -1.        ]
 [-0.59158963 -0.45041365  0.14461072 -0.67655818]
 [-0.50801667  0.70147     0.74410174  0.35846291]
 [ 0.52421407 -1.         -0.291692   -1.        ]
 [ 1.         -1.          0.16

[[ 0.27862213  1.          0.29646533 -0.01976631]
 [ 0.19375433 -1.          1.         -0.42068282]
 [-0.6490083   0.69712502 -0.94209097  0.55736819]
 [-0.89618693 -0.14340236 -1.          0.25659273]
 [ 0.20621553 -0.73287508  0.27110373 -1.        ]
 [-1.          1.          0.82205779 -0.0242184 ]
 [-0.34537195  0.50408044  0.06882997  1.        ]
 [-1.          1.         -0.13229156 -0.05325146]
 [ 0.51893552 -0.90546082  0.04396379 -0.664266  ]
 [-0.07008309  0.80343129 -0.00315966  1.        ]
 [-0.33341486  1.          1.          1.        ]
 [ 1.         -0.19425888  0.23255653 -0.30299518]
 [-0.31994534 -0.02348049 -0.47604846  0.89648087]
 [ 0.12049251  0.34785678 -0.25416801  1.        ]
 [ 1.          0.52757409 -0.78830845  0.02777465]
 [-0.04265572  0.15682349 -0.37537094  0.07262202]
 [ 0.37626488  1.         -1.          1.        ]
 [ 0.21535785  0.74887412 -0.1028005   0.28660116]
 [ 1.         -0.79186513 -0.62609868 -0.90166514]
 [ 0.41460492  0.97138018 -1.  

[[-0.43590825 -0.42640383 -0.71844994  0.63097414]
 [ 0.50536789  0.02416046  0.8830615   0.59835611]
 [ 1.         -0.52793892  1.         -1.        ]
 [ 0.33269199 -0.84183297  0.25492761 -1.        ]
 [-0.81324281  0.98352609 -0.34399614  1.        ]
 [-0.11778383 -1.          1.          0.20196273]
 [-0.25662923  1.         -0.321008    0.97378725]
 [-0.56766688 -0.91781802 -1.         -0.50866676]
 [-0.64379474  1.          0.32642491  1.        ]
 [-1.          1.         -1.          1.        ]
 [-1.         -0.12652334 -1.         -0.61016215]
 [-0.37091714  0.35628384  1.          0.22324936]
 [-1.          0.06975465 -0.0781656  -0.48191421]
 [-1.         -0.21054937 -0.62979202 -0.36954511]
 [ 1.         -0.9321929  -0.27371434 -1.        ]
 [ 1.          0.89653247  0.84059879  0.53970633]
 [ 0.11235397 -0.88770389 -1.          0.17755193]
 [-1.          0.0420681  -1.         -0.46940726]
 [-0.32048638 -1.         -0.17028647  0.51533391]
 [ 1.          0.15654088  0.32

[[-0.22463196 -0.51176176  0.03251169 -1.        ]
 [ 0.6640019  -0.62549651 -0.32465482  0.49066409]
 [-0.35654715 -0.60897634 -1.          0.05645105]
 [ 1.         -1.         -1.          0.42345661]
 [-0.53144643  0.99015541 -0.87833801 -0.17300442]
 [-1.          0.55365862  0.72594207 -0.38413519]
 [-1.         -1.          1.          0.33294919]
 [-0.16710032 -1.         -0.33218176  0.34108518]
 [-0.06062739  0.26190065  1.          0.66254562]
 [-1.         -0.9758421  -0.24886749  0.38328936]
 [-0.27513272 -0.04232912  0.85682947  0.50581762]
 [-0.09865274  0.30258785  0.3783012   1.        ]
 [ 0.27069671  0.37572434  0.48343779 -0.41123099]
 [ 0.0236415   0.46688807 -0.96665151 -0.71587594]
 [ 1.         -1.         -1.         -1.        ]
 [ 1.          0.22905805 -0.61150241 -1.        ]
 [-0.20648978  0.92450584 -0.99519416  0.6110006 ]
 [-1.         -0.78595602  0.23486077 -0.61335275]
 [-1.          0.54199215 -0.55840215 -0.47574677]
 [ 1.         -0.57479879  0.09

[[ 0.82080648 -1.         -0.10556972  0.95562974]
 [ 0.42357629 -1.         -0.38156722 -1.        ]
 [ 0.3489647   0.17369521 -0.60379421  1.        ]
 [-0.21458952 -0.78325786 -1.         -1.        ]
 [ 0.68626456  1.         -1.          1.        ]
 [-0.26627844 -0.92526976  0.44056751 -0.1542247 ]
 [ 0.40470224  0.65280704 -0.13117344  1.        ]
 [ 0.77513161 -0.30538337  1.          0.36346421]
 [-0.67970952 -0.31376212 -1.         -0.27296205]
 [-1.         -0.2003827   0.40643538  0.64995498]
 [-0.83387942  1.         -0.21770378 -0.09476689]
 [ 0.19809347 -1.          1.         -0.6151223 ]
 [ 0.31903387 -0.07758962  0.21885788  1.        ]
 [ 0.15142497 -0.74149142 -0.18052428  0.41299566]
 [ 0.45432973  0.05249447  0.24379701 -0.26624075]
 [ 1.         -1.          0.03775748 -1.        ]
 [ 1.          0.13910323 -1.         -1.        ]
 [ 1.         -0.49293528 -0.85360632  1.        ]
 [-1.         -0.23801404 -1.          0.57291654]
 [ 1.         -0.28669607 -0.21

[[-0.29958838 -0.11038068 -0.74462784  0.37548791]
 [-1.         -0.4757268   0.73418269 -0.40566732]
 [ 0.31482517 -0.90508487  0.19308355 -0.79865504]
 [ 0.9790741   1.         -1.         -0.73165899]
 [ 0.22229794 -0.37969296 -0.97613808 -0.78695603]
 [ 0.51766661  0.46032864 -0.21338315 -0.90960906]
 [-1.         -0.91519741  0.01206978  1.        ]
 [-0.19866563 -1.          1.         -0.2746662 ]
 [ 0.97161976 -1.          1.          1.        ]
 [-1.         -0.46906596  0.86764338  0.58675967]
 [ 0.20159324 -1.         -0.42341879 -0.30471078]
 [ 0.00490558  1.          0.74497517  0.34729719]
 [ 1.         -0.94881058  0.60189878  0.0830104 ]
 [ 1.          0.26824745  0.39124416 -0.60802104]
 [ 0.20161934  0.06577704  0.4191118   0.05458512]
 [ 0.59390166 -0.16477605 -0.58888643 -1.        ]
 [-0.46689944  0.31944536 -0.40158745 -0.27209176]
 [ 0.97334411  1.          0.13779661  0.49850821]
 [ 0.82876585 -0.1969192  -1.         -0.81939641]
 [-1.         -0.69489509 -1.  

[[-0.73585604 -0.01278133  0.63081618 -0.89596246]
 [-0.34698351  0.07146807  0.76827144  0.48497235]
 [-0.78879566  0.43070161 -0.41954355 -0.89627355]
 [ 0.6809583   0.56771049  1.          0.79139165]
 [-0.26068927 -1.         -0.50331006  0.08927859]
 [-0.60927679 -0.18673584  0.84790251 -0.21064865]
 [-0.99697391 -1.         -1.         -1.        ]
 [-0.51013272  0.64125831 -1.         -0.00816655]
 [-0.47775273 -0.58564611  0.30063039 -0.97442197]
 [-0.46317943 -0.133345   -0.76168488 -1.        ]
 [ 1.          0.29102619 -0.49567612  0.92118339]
 [-0.02930079  1.         -0.84881168 -0.17261959]
 [ 0.42020994  0.68632488  0.69144993 -1.        ]
 [ 1.          1.         -1.          0.51221165]
 [ 0.08875938  0.15900456 -1.          0.87547295]
 [-0.65338922 -0.83589704  1.         -1.        ]
 [ 1.         -0.76070186 -0.65204542 -0.7611693 ]
 [ 0.82165319  1.         -0.32707372  0.3892525 ]
 [ 0.8521774   1.          0.25457378 -0.72232651]
 [-1.         -0.76339263  1.  

[[-0.46111524 -1.         -0.53953314 -1.        ]
 [-0.42272323  0.34266924 -1.         -1.        ]
 [-0.4347204   0.60479363 -0.40378892  1.        ]
 [-0.14944546  1.         -0.36082431 -0.10446131]
 [ 1.          0.01739347 -0.45954538 -0.82678737]
 [ 0.62453313  1.         -0.84925567 -1.        ]
 [ 1.         -0.71213142  0.26219359 -1.        ]
 [ 0.19005216  1.         -1.         -0.36324539]
 [ 1.          0.19425288  0.39831888 -1.        ]
 [-1.         -1.         -1.          0.14160004]
 [-0.74154806  0.25220517  0.83071719  1.        ]
 [-0.02870474 -0.35448193 -1.          0.42777631]
 [ 0.00163924 -1.         -0.13264887  0.01635689]
 [ 0.67600105 -0.6580299  -0.16034902 -0.62045197]
 [-0.85719422 -1.         -0.50008821 -0.24891939]
 [-0.56753635 -1.         -0.11248536 -0.85619153]
 [ 0.81247316  0.02215076 -1.          1.        ]
 [-0.51430362  0.70789368  0.50727043 -0.24178883]
 [-1.         -0.02473866 -0.1311262   0.31851127]
 [-1.         -1.          1.  

[[ 0.5125294   0.52467674 -0.4774581  -0.29578808]
 [ 1.          0.87700366 -1.          1.        ]
 [-0.77888695  0.42028066 -0.87703943  0.11636496]
 [ 1.          0.6632203  -0.36990711  1.        ]
 [ 1.         -1.          0.18753833  0.33571618]
 [ 1.          0.85596165 -1.          0.89449413]
 [ 1.          1.          1.          1.        ]
 [ 0.45843755 -1.         -0.97171284  1.        ]
 [-0.95383688  0.62058545 -0.92080012 -0.73302899]
 [-1.          0.72440337 -1.         -0.65895263]
 [-1.         -0.79630083  1.         -0.70333963]
 [-1.         -0.44247307  0.07049952  1.        ]
 [-0.35462511 -0.07971635  0.60936071  0.08545227]
 [ 1.         -1.          0.85497366  0.67172754]
 [-0.41424903 -0.99553415  1.          0.53837917]
 [-1.          0.93119516 -1.         -0.42728429]
 [ 0.4554878  -0.91543138 -1.          0.10375498]
 [ 1.         -1.          0.97280807 -1.        ]
 [-0.80324681 -0.40782879 -0.36775243 -1.        ]
 [-0.40439051  1.         -1.  

[[ 1.          1.          0.15885174  0.37617169]
 [ 1.          1.         -0.48877721 -0.56041334]
 [-0.04868508 -1.          1.         -0.43510877]
 [-0.94037246  1.         -0.71655054  1.        ]
 [ 0.10469001  0.41113843 -0.17206995 -0.15210995]
 [-0.12134787 -0.02385542  1.          0.68076092]
 [ 0.48673588 -0.58935519 -0.04860709 -0.82227176]
 [ 0.26688293  1.          0.12145903  0.04235245]
 [-0.11410661  1.          0.95025909 -0.70625826]
 [-0.24029851  1.          0.79723026 -0.66169719]
 [ 0.13986998  0.84768857 -0.3718102  -0.13851882]
 [-0.67931304 -1.         -1.          1.        ]
 [-0.24048785 -0.51948925 -1.          1.        ]
 [-0.73121151 -0.08406272  0.52840179  0.17049143]
 [-0.39096598 -1.          1.         -1.        ]
 [-0.60888811  0.92589529 -0.84725127  0.46198859]
 [ 0.63102241 -1.         -0.64825628  0.5316037 ]
 [-0.274839    0.61721979 -0.26072793  0.58583601]
 [ 0.37721456 -0.64995953  0.85714231 -1.        ]
 [ 0.68776845  0.68549847 -1.  

[[-0.37629021  0.52676306  0.02362859 -1.        ]
 [-1.         -0.84829789  0.84329361 -0.31789567]
 [-0.53937882 -0.57931067  0.35134094  0.25942855]
 [ 1.         -1.          0.50111509 -0.10869209]
 [-1.          0.40389567 -0.08766049  0.29478906]
 [ 0.13191001 -0.92295035 -1.          1.        ]
 [-1.         -0.24029828 -0.45255026  0.77775135]
 [-0.24695938  0.7275737   0.04447387 -0.94527067]
 [-1.         -1.         -0.76131809  0.53125852]
 [ 0.03225241 -0.37474404  0.3673494  -0.38320511]
 [ 1.          0.59225332  0.84312614 -1.        ]
 [ 0.44580557 -1.         -0.17210535  0.58860566]
 [ 0.26949787  0.3313268  -0.6071407   0.66723178]
 [ 0.50123666 -0.25444865  0.00197084  0.17059797]
 [-1.          1.          1.          0.53027539]
 [-0.10160179  1.          0.38420069 -1.        ]
 [ 1.          0.50992218 -0.02793798  0.65400395]
 [-1.         -0.51873111 -1.          0.05346871]
 [-0.90283167 -0.06238897  0.52502376  0.27137411]
 [-0.57216051  0.53751777 -1.  

[[-0.21564953 -0.9366109  -0.85764332  0.99210771]
 [ 0.35954022 -0.26449273  0.75589328  0.1181687 ]
 [-0.58780084 -0.62498751 -0.88554252  0.80755034]
 [ 0.64644961  0.34739638  0.95203486  1.        ]
 [ 0.33985274 -1.          0.03690575 -0.31169902]
 [ 0.95712461  0.0171578  -1.          0.29026262]
 [ 0.57272684  0.92562562 -0.17984107 -1.        ]
 [ 1.         -0.56634764 -1.          1.        ]
 [ 0.8681033  -0.19019966  1.          0.28419701]
 [-0.27963637 -0.12473626 -0.04808641  0.86038128]
 [-0.12084423 -0.04004693  1.          1.        ]
 [-1.          1.          1.         -0.20951476]
 [ 1.         -1.         -0.72296285  0.10834102]
 [-0.10011272  0.54224049  0.38520514 -0.32497847]
 [ 0.9225064  -0.46188455  1.         -1.        ]
 [-0.13024691  0.43349848  0.44131965 -0.13020657]
 [-0.79936372 -0.31033412 -0.76861536 -1.        ]
 [ 0.44639745  0.08806034 -0.14499105  0.03010265]
 [-1.         -1.         -1.         -0.77307527]
 [-0.54859046  1.         -1.  

[[ 1.         -0.84037095  1.          0.0749927 ]
 [-0.56261385  0.2637426  -0.65441253  0.70806376]
 [ 1.         -1.         -0.96524916  0.66001402]
 [-0.95070876  0.20965061 -0.84204721  0.64027819]
 [ 0.0807992   0.47296175 -0.0261043   1.        ]
 [-0.64115624 -0.29242332 -1.         -0.27027325]
 [-0.38802773  0.66397748 -1.          0.35036135]
 [ 1.         -0.19876842  0.07525419 -0.26793721]
 [ 1.          0.26235609  1.         -1.        ]
 [-0.62783045  1.         -0.90585277 -0.98020081]
 [ 1.         -0.83083974 -1.         -1.        ]
 [-1.         -1.         -0.46553161  0.85198411]
 [-1.          0.63880342  0.21408526  1.        ]
 [-0.46633946 -1.          0.62052142  0.43314028]
 [ 1.          1.         -0.30509398 -0.94950029]
 [ 1.          0.41403285 -1.         -0.028843  ]
 [-1.         -0.59955541 -0.04767779 -0.59792718]
 [-0.14494312  0.03932276 -0.71364866 -0.83674776]
 [ 1.          1.          1.          1.        ]
 [ 0.77423098 -1.         -1.  

[[ 1.          1.         -0.40208082 -0.55663526]
 [ 1.          0.1241534   0.1688883   1.        ]
 [-0.36157655 -0.78643502  0.73755098  0.02755418]
 [ 1.          0.23073775 -0.50433256  1.        ]
 [-1.         -0.67265361  1.         -0.94996065]
 [ 1.         -0.65425646 -0.55898943  1.        ]
 [-0.64910766 -1.          0.35128767  0.39166008]
 [ 1.          0.41593375  1.          0.34999464]
 [-0.21208611 -0.76939753 -1.         -0.27872748]
 [ 0.98197975 -1.         -0.44742036  0.80391301]
 [-0.1868787  -0.04261225 -0.2803367  -0.40136461]
 [ 1.         -0.32955426 -0.78928267 -1.        ]
 [-0.72371997 -0.90112589  0.80094815 -1.        ]
 [-0.71357111 -0.33341267  1.         -0.83496767]
 [-0.51842258 -0.0698818  -1.         -1.        ]
 [-0.77099379  0.95486487 -0.26904797  0.20046637]
 [ 1.          0.34039509 -1.         -1.        ]
 [-0.52268212 -0.42306018  0.97131118 -0.77776376]
 [-0.74244245 -1.         -0.46005939  1.        ]
 [-1.         -0.02749343  1.  

 [-0.62419476  1.          1.         -0.15448786]]
[[ 1.         -0.95360052  1.         -1.        ]
 [-0.38269074  0.00374823 -0.51096783  0.50697821]
 [-0.74870511  0.33721398 -0.9548824   0.23066293]
 [ 1.          1.          0.43250498 -0.58270948]
 [ 0.95311437  0.28701913  1.         -0.13248326]
 [ 0.83440404  0.68011591 -0.0011291  -0.03446535]
 [ 0.43503011 -0.62738465  1.          1.        ]
 [-1.          0.8070112   0.41656031 -0.02022016]
 [ 0.6235636  -0.35844741  1.         -0.19481416]
 [-0.13250775 -0.87904642  0.45217283 -0.00544219]
 [ 0.92971396  0.41864594  1.         -1.        ]
 [ 0.36194856  0.1796931  -0.89262398  0.58663399]
 [ 1.          1.          1.          0.87243248]
 [-0.91384592 -1.         -0.12398726 -1.        ]
 [ 1.          1.          0.20823918 -0.52341146]
 [-0.8644185   0.33640021 -0.83080179  1.        ]
 [-0.24200247 -0.56773438 -0.22743556 -1.        ]
 [ 1.          0.52841586 -1.         -1.        ]
 [-1.          0.50143776  1. 

[[ 0.54082191 -1.          0.03785206 -1.        ]
 [ 0.58049872 -1.          1.         -1.        ]
 [ 0.09302003 -0.97788368 -1.          1.        ]
 [-0.57839547 -1.          0.33964415 -1.        ]
 [-0.31961613  0.39805769  1.         -0.68552789]
 [-0.22001494  0.92643382 -0.08013054  1.        ]
 [-1.          0.67704664 -0.2231873   1.        ]
 [ 0.7902563  -0.06587538  0.89365448 -0.35290572]
 [-1.          0.71406344  0.93893831  1.        ]
 [-0.93689224  0.32597907 -0.51861928  1.        ]
 [ 0.07876487 -1.         -0.65263502  0.31621445]
 [ 0.78879816  0.25056848  1.         -1.        ]
 [-0.37258513 -1.         -0.70853895 -1.        ]
 [-1.         -0.13168878  0.60941553 -1.        ]
 [-0.48725511 -1.          0.60838794  0.89536976]
 [-0.85835596  0.8624676   0.08520448  0.41892657]
 [-0.22726289 -1.         -0.58632843 -0.17852927]
 [-0.70850929  0.06839851 -0.94651943 -0.41938789]
 [ 1.          1.         -1.         -0.20551055]
 [-1.         -0.05703018 -0.52

[[-1.         -1.         -0.07935532  1.        ]
 [-1.         -0.11081424 -0.1105621  -0.85634953]
 [ 1.         -0.08621222 -0.60424979 -0.06645326]
 [-0.24589643 -0.72912255 -1.         -0.23718492]
 [ 0.94333657  0.70221515 -0.54626779 -1.        ]
 [-0.0490257   1.         -1.         -0.40388653]
 [ 0.65224351 -1.          0.81183709 -0.96683115]
 [ 0.57227628  0.8612784   0.40221728  0.21396482]
 [ 0.67269851  0.34748586 -1.          0.49282199]
 [-0.07782375  0.38459335  1.         -0.8980225 ]
 [-1.          1.          1.         -1.        ]
 [ 0.23662434  1.          0.43745072 -0.31654813]
 [-0.88842664 -0.07108199 -0.59298373  0.5314694 ]
 [-1.         -0.32476132 -0.17799994  1.        ]
 [ 1.         -0.24382083 -0.94713126  1.        ]
 [ 0.67442701  0.09261843  1.         -0.35938388]
 [-0.39034971  1.         -1.          0.68563911]
 [ 0.88877919 -0.99160946  0.14503241  0.65260808]
 [-0.17074905  0.94118433 -0.35647748 -0.03532696]
 [ 0.11839542  0.45267708  0.06

[[-0.88241391 -0.82285111  0.13405573  0.37632834]
 [ 1.         -1.          0.37837078 -0.4733138 ]
 [-0.60803215 -1.         -0.42196645 -0.05086287]
 [-0.28617829 -0.9389048   0.26215187 -0.66554406]
 [-0.60567236  1.         -0.02313828  0.4338154 ]
 [ 0.629099   -0.17561877 -0.5676111  -0.20660621]
 [-0.32543766 -0.04985201 -0.265163    0.12893181]
 [-1.          0.0198318   0.39960873 -0.27609184]
 [-0.65990609  0.60741581 -0.19020179  0.43051684]
 [ 0.78009032  0.77170514 -0.12512674  1.        ]
 [-1.          1.         -0.7294555   0.17703829]
 [-0.46321874  0.01814461 -0.8962153   0.66440508]
 [-0.46723597  0.00871143 -0.46464844 -1.        ]
 [-0.08771125 -0.05314918 -1.          1.        ]
 [-0.24348989 -0.49326398 -0.69274839 -0.67343033]
 [ 1.          0.34289912  0.74744599 -0.10937006]
 [-1.         -0.6963076  -0.63481976 -0.73931946]
 [-0.00928163 -0.21369353 -0.31766938 -0.1210803 ]
 [-1.         -0.04377722  1.          0.23268911]
 [ 1.          1.         -1.  

[[ 0.9340563   0.95550345 -0.32714317  1.        ]
 [ 0.64869563 -0.76852574  0.61459325  0.03625302]
 [ 0.34152286  0.47990944 -0.1000088   0.76994143]
 [-0.35257069 -1.          0.43958043 -1.        ]
 [-0.97834054  1.         -1.          1.        ]
 [-0.99160998 -0.84007495  0.78070336 -0.6364854 ]
 [ 0.41957805  0.04882792  0.26681969  0.91358813]
 [-0.85508451  0.4057153  -0.67618303 -1.        ]
 [ 0.7232582  -0.59975948 -0.00551457  0.17125177]
 [ 0.23493179  0.49867634 -0.7601764  -1.        ]
 [ 0.42112568  1.         -0.57897065  0.61186838]
 [ 0.28037079 -0.77614011  1.         -0.57153195]
 [-0.15838241 -1.          0.67513036 -1.        ]
 [ 1.          1.         -0.66225058 -1.        ]
 [-1.         -0.63451152 -0.67172292  0.54304351]
 [-1.         -0.71037564 -0.20036023  1.        ]
 [ 1.          0.85225192 -0.48414362 -0.3325518 ]
 [-0.46906063 -0.85509289 -1.         -1.        ]
 [ 0.10033606  1.         -1.          1.        ]
 [ 0.1550293   1.          0.21

[[ 0.04512047 -0.83388285 -0.43354479 -0.6813604 ]
 [-0.94053144  0.33012068  0.97586874  1.        ]
 [-1.         -0.07675161  0.39461359  1.        ]
 [-1.         -0.60951529 -0.31157999  0.0368618 ]
 [-0.21864441  0.92217239 -0.58617104 -0.31975073]
 [ 0.01143116  0.55485452 -0.35563166 -0.65117716]
 [-0.94174951  1.         -1.         -0.10286706]
 [ 1.          0.09204177  0.81845774  0.10702318]
 [ 1.          1.         -0.23039859  0.49918245]
 [ 0.63947629  0.5446325  -0.31770462  1.        ]
 [-0.14089744  1.          0.29838609  0.73976081]
 [ 0.70380015  1.         -0.56565622 -0.47195703]
 [ 0.43659853  1.         -0.7435563   1.        ]
 [ 0.72527696  0.11769377  1.          1.        ]
 [-0.8288039  -1.         -1.         -0.26863801]
 [ 0.94166748 -0.46398151  1.          0.58057842]
 [ 1.         -0.31964962 -1.         -1.        ]
 [-0.42006764  1.         -0.89489835  1.        ]
 [-0.05516236 -1.         -0.6009787   0.43383463]
 [-1.          0.05329748 -0.96

[[ 7.74136501e-01 -1.00000000e+00 -7.71100641e-01  2.58826687e-01]
 [-6.36268806e-01  1.00000000e+00  8.32942655e-01 -1.81441399e-01]
 [-3.49166593e-01  7.73558198e-01 -6.47695882e-01  8.43069468e-01]
 [-6.60782886e-01  1.79276832e-01 -2.08136154e-01  1.00000000e+00]
 [-4.16403013e-01  1.56097429e-01 -2.21620846e-01 -3.30850262e-01]
 [-1.00000000e+00  1.44323201e-03 -7.88417400e-01  2.53680503e-01]
 [-7.78814192e-01 -2.51321329e-01 -9.34311815e-01 -1.00000000e+00]
 [-1.34698931e-01  1.92811036e-01 -1.00000000e+00 -7.51921035e-02]
 [ 1.00000000e+00  4.82672984e-01  2.84428149e-01 -5.02200680e-01]
 [ 4.33285807e-01 -1.00000000e+00  2.16583156e-01 -3.31255008e-04]
 [-3.54440630e-01 -5.10199282e-01 -1.00000000e+00 -1.08002799e-01]
 [ 8.30691811e-01  6.50679697e-01  4.19531407e-01  1.00000000e+00]
 [ 3.80366510e-02 -1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-7.80648643e-01 -1.80412616e-01 -1.00000000e+00  1.00000000e+00]
 [ 3.99517946e-01  3.65565663e-02  1.88360074e-02  1.00000000e

 [-0.65382194  1.          0.10494084  0.35579537]]
[[ 0.82880439 -1.          1.          0.54991394]
 [ 1.         -0.97957307 -0.21642967  1.        ]
 [ 1.          0.24171277 -0.39177149  1.        ]
 [-1.         -0.84381596  1.          0.23117902]
 [-1.          0.26841033  0.73983066 -1.        ]
 [ 0.82221783 -1.         -0.53458367  0.44961648]
 [ 1.         -1.         -0.39149019 -1.        ]
 [ 0.28370208  0.37540787  0.95234384 -0.7805785 ]
 [-1.          0.05039104  0.10120985 -1.        ]
 [ 0.92113895  1.          0.43126636 -1.        ]
 [ 1.         -0.22676105  0.01326089 -0.74208975]
 [-0.29754572  0.00619131 -0.95041575  1.        ]
 [ 0.97192113  0.53427685  0.17585788  1.        ]
 [-0.04479429  1.         -0.18610992 -0.0279072 ]
 [-0.54951656 -0.51756543 -0.61580797  0.02288444]
 [ 0.45984022 -0.92276535  0.8697592  -0.72843496]
 [-0.43611405 -0.00461975  1.          0.03149959]
 [-0.23924423  0.49662812 -1.          1.        ]
 [ 0.01612787 -0.18717415 -0.6

[[ 0.52250153 -0.57173933  0.39414868  1.        ]
 [ 0.47128253  0.58595635  0.01312713  0.2305236 ]
 [-1.          0.76986919 -1.          1.        ]
 [-1.          0.38463752 -0.07336514  0.45408448]
 [ 0.21663172  0.08584236 -0.58984069 -0.69167641]
 [ 0.16686571 -0.42268874  1.          0.88016979]
 [-1.         -0.96814805 -0.84540376 -0.22914384]
 [ 0.7039793   0.1177734  -1.         -0.14462213]
 [-0.03362328  0.19240585  0.18381207 -1.        ]
 [-0.99096519  0.8184406  -0.47579592 -1.        ]
 [-0.55491758  1.         -0.8843396  -0.15646028]
 [-1.          0.13465125  0.55585338 -1.        ]
 [ 0.45644916 -1.         -0.90365776  1.        ]
 [-0.76041128 -0.33532199 -1.          1.        ]
 [-0.69747708  0.84701493  0.44849408  0.17744552]
 [ 1.         -1.         -0.13616924  0.28262033]
 [ 0.14582179 -0.07279009 -1.         -0.52482062]
 [ 1.          0.36586563 -0.59890678  1.        ]
 [-1.          1.         -1.          1.        ]
 [-1.          1.          0.17

[[ 1.         -0.3853157   0.89086506  0.57636992]
 [ 1.         -0.83822771 -1.         -1.        ]
 [-0.59761605  0.49119524 -1.         -0.20189356]
 [-0.85323017 -1.         -0.10366444 -1.        ]
 [ 1.          0.40475602  0.91043411 -1.        ]
 [ 1.          0.45094643 -0.10565094 -0.57098075]
 [ 0.22637469  1.          1.         -0.13970643]
 [ 1.         -0.76067211  0.02099542 -0.90625743]
 [-0.46059176 -1.          1.          0.9361918 ]
 [ 0.71623343 -0.9575791  -0.08917423  0.7981207 ]
 [ 1.         -0.0381845  -0.90588897  0.46959546]
 [ 1.          1.         -0.60670711 -1.        ]
 [ 0.39470778  0.57195404 -0.19459448 -0.44241939]
 [-1.         -0.41375061  0.25645608  1.        ]
 [-0.30746664  0.58390108  1.         -0.55170446]
 [ 0.43817618  1.          0.58013421  0.02179079]
 [-0.05490475 -0.29064836 -1.          0.92523963]
 [-1.         -1.          0.65422858 -0.43913181]
 [ 0.50122441  0.675153    0.7804967   0.03112369]
 [-1.         -0.57979659  0.01

 [ 0.20784038  1.          0.6785035  -1.        ]]
[[-0.13620157  0.94108991 -0.07699342  0.33718167]
 [-0.14189152 -0.08225491  1.         -1.        ]
 [ 0.14126409  1.         -0.40515151  0.75113961]
 [ 0.75984891 -0.10566008 -1.          1.        ]
 [ 1.         -1.          0.3314549   0.99081604]
 [-1.          1.          1.         -0.25462997]
 [-0.31588566 -1.          0.20148887 -0.08755216]
 [-0.16190489  1.         -0.52358599 -1.        ]
 [ 1.          0.07210611  1.          0.0673587 ]
 [-1.         -1.          0.52404633 -0.6010431 ]
 [-1.         -0.23019574  0.04958308  1.        ]
 [ 0.19376375 -0.13316638  0.25769986 -0.06502681]
 [-0.13466265 -0.03526684  1.         -0.02876743]
 [-0.72481585 -1.         -0.35516291  1.        ]
 [-0.42372081  0.14525124 -0.05136061  0.08089678]
 [-0.38751262 -0.69730488  0.87999492 -1.        ]
 [ 1.         -0.31629082  0.18937245 -0.01717364]
 [-0.89534762  1.          0.06586728 -1.        ]
 [ 1.          0.72818    -0.6

[[ 0.47489978  0.28742274 -0.84332916  0.36586175]
 [-1.          0.34281521  0.93338789  0.26453218]
 [-0.89894542  0.63313766 -0.91020273 -0.02368174]
 [ 0.16785646 -0.01635896 -0.18008339  0.64662676]
 [-0.35471419 -1.         -0.40810387  1.        ]
 [-0.79448487  0.39150135 -1.          1.        ]
 [ 0.21358416  0.75985731  0.48223275  0.57113836]
 [ 0.65386472 -1.         -0.06668779  0.0476578 ]
 [-0.97481625 -0.18964376  0.57921164 -0.30455942]
 [ 0.10915662  0.45329045 -1.         -0.52865237]
 [ 0.93727178 -0.42927402 -0.09783326 -0.63804151]
 [ 0.31179889 -1.          0.3273206  -0.35817412]
 [-0.43199165 -0.1845645   0.13426326  1.        ]
 [ 0.30896298 -0.83340263 -1.         -0.55975967]
 [ 1.         -0.50584988  1.         -1.        ]
 [ 0.50162853 -1.          0.33663636 -1.        ]
 [-0.62751096  0.67907928 -0.03092421 -0.30227377]
 [ 0.22402444  0.15248506  0.24401768  0.48520249]
 [ 1.         -1.          0.28567255  0.69903948]
 [ 0.52948748  0.95034617  0.39

 [-0.5426131   1.         -0.4048992  -0.18971641]]
[[-1.          0.04774412 -0.42154302 -0.3883393 ]
 [-1.         -1.          1.         -0.17165428]
 [ 0.32849256  0.62260187  0.46750175  0.02163112]
 [-0.48850869 -0.2411984   0.37110317  0.39464554]
 [-0.64796215 -0.57099676  0.03516678 -0.82980963]
 [-0.21016971 -0.17025828  0.75751723 -0.3281508 ]
 [-1.          1.         -0.12637771  0.54633417]
 [-0.17181281  0.04669498  0.50255857 -0.52531726]
 [ 0.32471386 -0.55168805 -0.48050513  1.        ]
 [-0.74953976 -1.          0.52945682  1.        ]
 [ 0.30943776 -0.3945319  -1.         -1.        ]
 [-0.13612361 -0.71575871  0.31154138  0.37155354]
 [-0.76247293  1.          1.          0.79675001]
 [ 0.36200694 -0.13372625  0.15175122  1.        ]
 [ 0.55078385 -0.93251756 -0.43611369  1.        ]
 [-1.         -0.66347193  0.0579447  -0.69991599]
 [-0.54274833  0.37922567 -1.          0.48733473]
 [ 0.485708   -1.         -0.4823259   0.40214436]
 [-0.10905423 -0.31827696  0.8

[[-1.          0.03707551  0.90867218 -1.        ]
 [ 0.61298975 -1.          0.49856999  0.13608451]
 [-1.          0.47767888 -0.05091211  0.34533627]
 [-1.          0.17989284  0.89893596  0.01192071]
 [-0.33543986  0.93123929  0.76185845 -1.        ]
 [ 1.         -0.04618047 -0.68069975  1.        ]
 [ 0.62480377  1.         -1.          0.46254942]
 [-0.74233723  0.34280441  0.31792351 -0.9673895 ]
 [-0.13221763 -0.94435588 -0.43622218  0.35247915]
 [-0.27151905  0.63448063 -1.          0.71582659]
 [ 0.08904981  0.43646821 -0.76090221 -1.        ]
 [ 1.         -0.74666405 -1.          0.90228361]
 [ 0.16140063 -0.57704303 -1.         -1.        ]
 [-1.         -0.13758658 -0.5503988  -0.5588137 ]
 [-1.         -0.62929003  0.21364362 -0.88553991]
 [-0.49853436  1.         -0.36287909  1.        ]
 [ 0.42992321 -1.         -0.9238465   0.0136739 ]
 [ 0.78025101 -0.14601174 -0.4760241   1.        ]
 [-1.         -1.         -0.44939197 -0.90262895]
 [ 1.         -1.         -0.70

[[ 1.         -0.22836187  0.66826169 -0.26858518]
 [ 1.         -0.55527839 -0.43340846  0.61918604]
 [ 0.15344236  0.00967042 -0.44825625  1.        ]
 [-0.83247964  0.49755957 -0.11133699  0.77135089]
 [-1.          0.00463682  0.55751149  1.        ]
 [ 0.76311579 -0.24099946 -0.7687034   1.        ]
 [-0.17887314  0.20007924 -0.16099464 -0.24988011]
 [-0.7058258  -0.02715337 -0.24455978  0.00301867]
 [ 0.15038592 -0.0021906   0.45555328 -0.28204539]
 [-0.67742308  0.58336098 -0.00244019  1.        ]
 [-1.          1.          0.67455752  0.27710034]
 [ 0.23552253  1.          1.          0.53128112]
 [-0.17368301  0.14556295 -0.93075681  1.        ]
 [ 0.37420554  0.62085544 -0.70166437 -1.        ]
 [ 0.44318752 -1.         -0.65174383 -1.        ]
 [-0.07868252  0.80841509 -0.31088631  0.43119611]
 [ 1.          0.39601325 -0.82407587 -0.28066097]
 [ 1.          1.         -0.67088404 -1.        ]
 [-0.8399381  -0.45164839  1.         -0.99611093]
 [-0.26894612  0.24483987 -0.03

[[ 1.          1.         -0.15687234 -0.7128337 ]
 [ 0.34001106 -1.         -1.          0.73928248]
 [ 0.0495505   0.17913834  0.20718593 -0.24546277]
 [-0.3311844  -0.3850835   0.35277976  0.03999905]
 [-1.          0.56042547  0.42727432 -0.79922857]
 [ 0.26704491 -0.11955227 -1.          0.24717645]
 [-1.         -0.76429613  0.45098021  1.        ]
 [ 1.         -1.         -0.9620455  -1.        ]
 [ 1.         -0.94947036  0.13449873 -0.15194006]
 [ 1.          1.          0.42670446  0.47523087]
 [-0.71333392  0.51687794  1.         -0.05456327]
 [-0.83573688  0.45423191  1.          0.5663135 ]
 [ 0.4094198  -0.16675717 -0.67601109  1.        ]
 [-0.28595983  0.00419545 -0.93104277 -0.01160521]
 [-0.81837131 -1.         -0.35392195 -0.35907355]
 [ 0.30235897  1.          1.         -1.        ]
 [-1.          0.08130663 -1.         -0.56478119]
 [ 1.         -1.         -0.75250652  1.        ]
 [-1.         -0.53600667 -0.68259856  0.54853951]
 [-0.10730815  0.26616391 -0.50

 [-0.51330239  1.          1.         -0.76105453]]
[[-0.74851589  0.857286   -0.88319617  0.69738377]
 [-0.40649551 -0.56373675 -0.8979096   1.        ]
 [-1.          1.          1.         -0.37738689]
 [-0.61680021 -0.76523225  1.          0.53617906]
 [-1.          0.90973952  1.          1.        ]
 [ 0.60532183  0.87231462  0.00819542  0.9938359 ]
 [ 1.         -0.40523003  0.45658188 -1.        ]
 [ 0.28426786 -0.83125476 -0.39478669 -0.95345697]
 [-1.          1.         -0.4435836   0.15624011]
 [-1.          1.          0.35612274  1.        ]
 [-1.          0.04588199 -1.         -0.78853141]
 [-0.42696926  0.22823354 -1.          0.72471856]
 [ 0.5952663   0.07293035 -0.71952786 -1.        ]
 [ 0.49420283  0.70824578 -0.56936723  0.29416106]
 [-0.63666452 -0.79394823  0.86168224  0.13784398]
 [-0.33095116 -0.21733367 -0.97126006 -0.29609889]
 [-0.0809389   0.55665862 -1.          1.        ]
 [-0.55757071 -0.12220833  1.          0.35273851]
 [-0.91016273  0.03504281  1. 

 [-1.         -0.45619545 -0.6268532   1.        ]]
[[-0.30396887  0.23344929 -0.59816318  0.51348995]
 [-0.15622111 -0.6511542  -1.         -0.73505468]
 [ 0.01134055 -0.40960639  1.          1.        ]
 [-0.0960485  -0.32245236  1.          0.21124558]
 [ 0.18464554 -0.02943086  0.16809826 -1.        ]
 [-0.18319489 -1.          1.         -0.45159162]
 [ 0.34550354 -0.23100509  1.          0.19392837]
 [-0.76763854  1.         -0.55327258  0.93507865]
 [-0.11231109  1.          0.48080359  0.92241035]
 [-0.17740184 -1.         -0.54960379  1.        ]
 [ 0.53018988  0.28105906  0.01307264  0.00524986]
 [ 0.33457905 -0.74260706 -0.17477573  0.4537497 ]
 [-0.00679135 -1.          0.75561742  0.32891747]
 [ 0.98212829  1.         -1.          0.42373428]
 [-0.16094816  0.99779116  0.22049463 -0.22084803]
 [-0.72944674 -0.58927661 -0.29371882 -0.80837909]
 [-0.25801518  1.         -0.94793681 -1.        ]
 [-1.         -1.          0.28289873 -0.48929108]
 [-0.39428585 -0.12357533  1. 

[[-1.         -1.          1.         -0.41874058]
 [ 0.46437043  0.62353468 -0.6894922  -0.36750308]
 [-0.06428011  1.          1.         -0.56711188]
 [-0.65585566  0.66994418 -0.74799988 -1.        ]
 [-1.          0.60595166 -0.99810079 -0.57586804]
 [ 0.14147343  0.53289921  0.1450498   1.        ]
 [-1.          1.         -0.09359558  0.10980489]
 [ 1.          0.03279579  0.51602013  0.37057235]
 [ 1.         -0.91878386 -0.60130158 -0.01062535]
 [ 0.42528076 -0.75665582  0.23218074 -0.59853608]
 [-0.54250553  1.         -1.          1.        ]
 [ 0.28720824 -0.70670825 -1.         -0.52364684]
 [ 0.53134427 -0.4504457   1.          0.0860426 ]
 [ 0.5981743   1.         -0.80655806 -0.74861292]
 [ 1.          1.          0.12589755  0.32889646]
 [-1.         -0.22066812  1.          1.        ]
 [ 0.85815492 -0.43086964  1.         -0.87226161]
 [ 0.23929665 -1.         -0.27082734 -0.23970719]
 [-1.          0.0835692   0.45541225  1.        ]
 [-1.         -0.81320181  0.05

[[ 1.         -1.          1.          0.02916976]
 [ 0.71616445 -1.          0.73914937 -0.07117549]
 [-1.          0.56296454  0.86982578 -1.        ]
 [-0.05153679  0.00599973  0.8238738  -0.03231978]
 [-1.          0.51801541  0.18182925 -0.26782813]
 [ 0.9774066   1.         -0.11309377  0.67408317]
 [-0.96434714 -1.          1.          0.5419702 ]
 [ 1.         -1.         -0.48857938  1.        ]
 [-0.94616693 -1.          0.51560726 -0.79945331]
 [ 1.         -0.09808797  0.92177721  0.05624644]
 [ 0.17281896  0.55482342  1.          0.82733894]
 [ 0.79905542  0.93482739 -0.57829173 -0.49718543]
 [ 1.          0.41650326  0.4544435   0.28206854]
 [-0.68171622 -1.          0.90948903  0.18642212]
 [-0.14503634  1.          0.32304814 -1.        ]
 [ 0.16400784 -1.          0.59421317  1.        ]
 [ 0.71353749  0.98896325 -1.          0.70904521]
 [ 1.          1.         -1.         -1.        ]
 [ 1.         -0.48423476 -0.18553241  0.78839208]
 [ 0.67497907  0.18806234 -0.89

[[-0.34021638  0.25557471  0.64818108 -1.        ]
 [-0.28568279  0.2701321   0.22934745  0.08022803]
 [ 0.9445363   0.38412261 -0.0113546   1.        ]
 [ 1.         -1.         -1.          1.        ]
 [-0.563654    0.89048035 -1.         -1.        ]
 [ 0.16831906  0.01657995 -1.         -0.10949781]
 [ 0.20007956 -0.37334039  0.26226634 -0.51380834]
 [-1.          0.17528071 -0.91935004  0.53919093]
 [ 0.13510926 -0.66495921 -1.         -0.91438392]
 [-0.61901416 -0.34211758  1.         -1.        ]
 [-0.00273421  1.         -0.23183786  0.20053953]
 [-0.54495275 -1.          1.          0.30244943]
 [-0.48080561 -0.66900223 -0.82005985  0.23470233]
 [-0.65169466 -1.          0.54974016  0.09636897]
 [ 0.48408842 -1.          0.74511587 -0.73452348]
 [-0.94235719  0.50760798  1.         -0.05758363]
 [ 0.94971891 -0.58140052 -0.60356632  1.        ]
 [-0.21938478  0.07371554 -1.         -0.23024135]
 [ 1.         -1.          0.44349944 -1.        ]
 [ 1.          1.         -0.75

[[-0.64119658  0.72235463 -0.75833634 -0.62061053]
 [ 0.06558753 -1.          0.28353216  0.21165016]
 [-1.         -0.31209793 -0.00290829 -0.34026218]
 [-1.         -1.          1.         -1.        ]
 [ 1.          0.3262837   0.97567639  1.        ]
 [-0.11355003  0.84789584 -1.          0.8804294 ]
 [-1.          1.         -0.26753195  0.509779  ]
 [-0.94721202  0.50241573 -1.          0.15739199]
 [ 0.46420245  0.22814946  0.01193894 -1.        ]
 [-0.05437793  0.21242932 -0.12732795  1.        ]
 [-1.         -0.23788276 -0.3921265   0.08544849]
 [ 0.48790048  0.23990336 -1.         -0.36241368]
 [-0.99466867 -0.71823741 -0.4145533  -0.66536371]
 [-0.83166098  1.          0.24043034 -0.49826709]
 [-0.41128357  0.89660913  1.         -0.92446577]
 [-1.          0.52157858  1.         -0.06939741]
 [ 0.3572857  -0.27440783  0.86804018  1.        ]
 [-1.         -1.          0.19202715  0.00501089]
 [-0.96095198  0.97608707 -0.80806416  0.8783037 ]
 [ 1.         -1.          0.68

[[ 0.92842802 -0.29999954  1.         -0.37764351]
 [-0.35711884  0.13601369 -0.15225811  1.        ]
 [-0.99012552  0.84964951 -0.68429426  1.        ]
 [-0.77221446  1.          0.57892319 -0.30283741]
 [ 0.12402036  0.94476603  0.01083299 -1.        ]
 [ 0.3731629   0.54827716 -0.55972881 -1.        ]
 [ 0.61159081 -0.02690992  0.48638101 -1.        ]
 [-1.          0.38365324 -0.5493547  -1.        ]
 [ 0.51991051  1.          0.07962665  0.27853015]
 [ 0.44760471 -1.         -0.0257023   1.        ]
 [ 0.01268865  1.         -0.91241966 -1.        ]
 [-0.97159112  0.24450941  0.53074616  0.15346928]
 [ 0.24088755 -0.70990208 -0.2546654   1.        ]
 [-0.74185387  0.28893505  0.44223555 -1.        ]
 [-0.6429761  -0.64822998  1.         -1.        ]
 [ 0.38040619 -0.21488675  1.         -0.38229907]
 [-0.00767712 -0.25688377 -1.          0.70377375]
 [ 0.64036922  1.         -1.          0.87668081]
 [-0.12699958 -0.52330655 -0.81995719  0.71323626]
 [-0.46420834 -1.         -0.77

[[-1.         -1.          1.         -1.        ]
 [ 0.34716479 -0.11090555  0.66289074 -1.        ]
 [ 0.91402376 -0.16037371  0.51818855  0.82052777]
 [ 1.         -0.17862777 -0.51339596 -0.40990668]
 [-0.68556925 -1.          0.63442002 -0.26658827]
 [ 0.15267871  0.27803645 -0.36221946 -0.89214797]
 [-1.          0.34525702  1.         -1.        ]
 [ 0.92967424  0.27068018  1.         -1.        ]
 [ 0.84561457  0.63008518  1.         -0.24444921]
 [-0.03161013  0.5581039  -1.         -1.        ]
 [-1.         -1.         -0.08009168 -0.39174721]
 [-0.25219873  1.         -0.66273241 -0.52062061]
 [ 0.80088656  1.          1.         -0.22625063]
 [-0.76929837 -0.3490021  -1.         -0.47508262]
 [-0.53576984  0.92917315  0.4737584   0.31799006]
 [ 0.33558239 -0.59014487 -0.24610452  0.41955967]
 [ 1.          0.95309663  0.54250568 -1.        ]
 [-0.54524644 -0.76294507  1.          1.        ]
 [-0.54153364  0.24107786 -0.57855859  0.92497215]
 [-0.77663217 -1.         -0.78

[[ 0.80602971 -0.37503368  0.77422072  0.95172684]
 [-0.6477575   0.02567131  0.44101006 -1.        ]
 [ 0.32333488  0.5764918  -1.         -0.96738031]
 [-0.00228659  0.39099833  0.60470045  0.20365455]
 [-0.43588027  0.92900735  0.50012767 -1.        ]
 [-0.6471998   1.          0.43365817  0.48689833]
 [-0.17580865  0.83087696 -0.46657944 -0.61483982]
 [-0.99594283  0.44166805  0.08626966 -0.53467016]
 [ 0.00615615 -0.84203856  0.8556637  -1.        ]
 [-1.         -0.81115831 -0.10892724 -0.00841042]
 [ 1.          1.         -1.          1.        ]
 [-0.195566    0.8890565  -0.08160264 -0.92558616]
 [ 0.21931454  1.         -1.         -1.        ]
 [ 0.89073292  1.         -0.87431167 -1.        ]
 [-0.57667099 -0.83019568  0.33831402 -0.11540196]
 [ 0.66226707 -1.         -0.91691897  0.54779775]
 [ 0.35152294 -0.27303439  0.52759074  1.        ]
 [ 0.44707525 -0.75690498  1.          0.3950295 ]
 [ 0.4672508  -0.72014744  0.64656085 -0.60130906]
 [-0.50253092 -0.67090684 -0.30

 [ 0.22984358  0.41524913 -0.08943239 -1.        ]]
[[-0.49953494  0.86473095  1.         -0.91954671]
 [-0.59160071 -1.         -0.51829145  1.        ]
 [ 0.66182189  0.42361395 -1.          1.        ]
 [ 0.69220449 -0.09151955  1.          0.27039604]
 [ 0.43991804 -0.24392323 -0.98162212 -1.        ]
 [-1.         -1.         -0.25624551  0.16634027]
 [-0.99899223  0.60723455  1.         -0.19298278]
 [-0.13042497 -0.76036154  0.91018808 -0.28637569]
 [ 1.         -1.         -0.08393909 -0.82333057]
 [ 1.          0.61952653  0.76561266 -1.        ]
 [ 0.79522429  0.84919657 -1.          0.85308428]
 [ 0.10418637  0.8445397  -0.1150387  -0.24394553]
 [ 0.1778133  -1.          0.40047503 -0.7647577 ]
 [ 0.96833114 -0.36414185 -1.          0.11328341]
 [ 0.18523523  1.         -1.         -1.        ]
 [-1.          0.3958923   0.91433919 -0.3313192 ]
 [ 0.34515811 -0.17695421  0.5798917  -1.        ]
 [-0.89614347 -1.          0.89086485  0.19411221]
 [ 1.          0.01681822  0.4

[[ 1.         -0.91355549  0.02891653  1.        ]
 [-1.         -0.02424527 -0.73643961 -0.29740401]
 [-0.74521155 -1.          0.24745362  0.7333326 ]
 [ 0.42396237 -0.58929938  1.          0.21881072]
 [ 0.1704995   0.01293554  1.         -0.77840404]
 [-1.         -1.         -0.02458706  0.25144375]
 [-0.70557813 -0.58600646 -1.         -0.03772826]
 [ 0.71050833  0.31687085  0.37907846  0.59591092]
 [-1.         -0.58860889 -1.         -0.29027115]
 [ 0.49265141 -1.         -1.          0.69930077]
 [ 0.53112661 -0.14606285  0.70857349  0.25011197]
 [ 0.39709531 -1.          0.50992019 -1.        ]
 [-1.          0.0438779  -1.         -1.        ]
 [-1.         -0.03870778  0.54969849  1.        ]
 [-1.          0.05409078 -0.54567118 -0.2016382 ]
 [-0.1821226   1.         -0.04762117  0.64995837]
 [-1.         -0.26353883  1.         -0.74045353]
 [ 1.         -0.32254813  1.         -0.97299283]
 [-0.69672165 -1.         -0.8518453  -0.3466862 ]
 [-0.89528616 -1.         -0.34

[[ 0.61281882 -0.96457328 -0.66283489  1.        ]
 [-1.          0.22715197 -0.55869424 -1.        ]
 [-0.80616548 -0.05253792 -0.30398869  1.        ]
 [-0.08911656  1.         -0.2389965  -0.63949029]
 [-1.          1.         -1.          0.14251922]
 [ 1.         -0.03531709  0.55432569 -0.35135192]
 [ 0.88567816  1.          1.          1.        ]
 [ 0.37444521 -0.61521587 -0.64333853 -0.40748299]
 [-0.60985276  0.66442866 -0.77488364 -0.48179793]
 [-1.         -0.97659499 -0.34789792 -1.        ]
 [-0.86531196  0.19681532  1.         -0.88587155]
 [ 1.         -0.50764233  0.58231992  1.        ]
 [ 1.          0.31590685 -0.8337182  -0.36532561]
 [-0.32124798 -1.          1.          0.32815481]
 [-0.9730559  -0.65952665 -0.4657336  -0.70244021]
 [-0.1906407  -0.60035562  0.79576409 -0.84272765]
 [-1.         -0.32644129  1.          0.76330046]
 [-1.         -1.         -0.74045123 -0.32680893]
 [ 1.         -1.          0.43001013  0.81041093]
 [ 1.         -0.1003151  -1.  

When finished, you can close the environment.

In [6]:
# Don't close it yet, we still need it for the training.
# env.close()

### 4. It's Your Turn!

Now it's your turn to train your own agent to solve the environment!  When training the environment, set `train_mode=True`, so that the line for resetting the environment looks like the following:
```python
env_info = env.reset(train_mode=True)[brain_name]
```

In [7]:
env_info


In [14]:
%load_ext autoreload
%autoreload 2

from p2_agent import A2C_Agent

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

def tensor(x):
    if isinstance(x, torch.Tensor):
        return x
    x = np.asarray(x, dtype=np.float32)
    x = torch.from_numpy(x).to(device)
    return x

states = env_info.vector_observations
state_size = states.shape[1]
action_size = brain.vector_action_space_size

agent = A2C_Agent( state_size, action_size, 1234, None, 16 )


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Creating model with  256  and  128  hidden layer sizes.
Creating model with  256  and  128  hidden layer sizes.
params:  tensor(0., device='cuda:0', grad_fn=<SelectBackward>)


In [73]:
episode = 100
nstepqlearning_size = 5
gamma = 0.99
entropy_weight = 0.01
gradient_clip = 5

for e in range(episode):
    env_info = env.reset(train_mode=True)[brain_name]     # reset the environment    
    states = env_info.vector_observations                  # get the current state (for each agent)
    scores = np.zeros(num_agents)                          # initialize the score (for each agent)
    episode_terminated = False

    while episode_terminated == False:
        l_states = []
        l_actions = []
        l_rewards = []           #np.zeros(( nstepqlearning_size, num_agents ))
        l_masks = []
        l_next_states = []
        l_values = []
        l_log_probs = []
        l_entropy = []

        nstep_memory_size = nstepqlearning_size 
        for i in range(nstepqlearning_size):

            # Get a(t) according to actor policy 
            (actions, log_prob, entropy, values) = agent.act(states)
            actions = np.clip(actions, -1, 1)                  # all actions between -1 and 1

            # Perform a(t) in all environments
            env_info = env.step(actions)[brain_name]           # send all actions to tne environment

            # get s(t+1), r(t) and wasLastAction(t)
            next_states = env_info.vector_observations         # get next state (for each agent)
            rewards = env_info.rewards                         # get reward (for each agent)
            #print("R:", rewards)
            #print("Rew: ", torch.from_numpy(np.asarray(rewards, np.float32)).unsqueeze(-1))
            dones = env_info.local_done                        # see if episode finished

            masks = 1 - np.asarray(dones, np.int)

            #mask = 1-torch.from_numpy(np.asarray(dones, np.int))  #.unsqueeze(-1)
            #print("D: ", type(dones))
            #print("D2: ", type(masks))
            l_states.append(states)
            l_actions.append(actions)
            l_rewards.append( rewards )
            l_masks.append(masks)
            l_next_states.append(next_states)
            l_values.append( values )
            l_log_probs.append( log_prob )
            l_entropy.append(entropy)

            # update score
            scores += env_info.rewards                         # update the score (for each agent)

            #print(values)

            states = next_states                               # roll over states to next time step
            if np.any(dones):                                  # exit loop if episode finished
                nstep_memory_size = i + 1
                episode_terminated = True
                break

        # get one prediction for the last estimated Q value
        (actions, log_prob, entropy, values) = agent.act(states)

        advantages = tensor( torch.zeros((num_agents, 1)) )
        returns = values.reshape(( num_agents, )).to(device)     # last Q value

        l_advantages = []    #np.zeros(( nstepqlearning_size, num_agents ))
        l_rets = []          #np.zeros(( nstepqlearning_size, num_agents ))
        l_masks = torch.tensor(np.array(l_masks)).to(device)        #.squeeze().cpu()
        l_rewards = torch.tensor(np.array(l_rewards)).to(device)    #.squeeze().cpu()

        for i in reversed(range(nstep_memory_size)):
            returns = l_rewards[i] + gamma * l_masks[i] * returns
            advantages = returns - l_values[i].reshape((num_agents, ))
            #print("adv:", advantages)
            x = advantages.detach()
            l_advantages.append( advantages.detach() )
            l_rets.append( returns.detach() )

        # bring log_probs list to Tensor with shape [ num_agents,nstepqlearning_size ] 
        #print(nstep_memory_size)
        logprobs = torch.cat(l_log_probs).squeeze()
        logprobs = logprobs.reshape(( nstep_memory_size*num_agents )).to(device)     

        ents = torch.cat(l_entropy).squeeze()
        #l_values = torch.tensor(np.array(l_values))    #.squeeze().cpu()

        #advantages_tensor = torch.tensor(np.array(l_advantages, dtype=np.float64)).to(device) 
        advantages_tensor = torch.cat(l_advantages, dim=0).squeeze().detach().to(device)
        #print("advantages_tensor", advantages_tensor)
        policy_loss = -(logprobs * advantages_tensor).mean()
        #print("Ent: ", ents)
        entropy_loss = ents.mean()
        #print("Ploss: ", policy_loss)
        #print("Entloss: ", entropy_loss)

        # train Actor
        agent.actor_optimizer.zero_grad()
        #print("ActorTensor: ", (policy_loss - entropy_weight * entropy_loss) )
        (policy_loss - entropy_weight * entropy_loss).backward()
        torch.nn.utils.clip_grad_norm_(agent.actor_net.parameters(), gradient_clip)
        agent.actor_optimizer.step()

        # train Critic
        agent.critic_optimizer.zero_grad()
        #print("l_rets:", l_rets)
        #print("l_values:", l_values)
        l_rets = torch.cat(l_rets, dim=0).squeeze().detach().to(device)
        l_values = torch.cat(l_values, dim=0).squeeze().to(device)
        #print("l_rets2:", l_rets)
        #print("l_values2:", l_values)
        v = 0.5 * ( l_rets - l_values )
        value_loss = v.pow(2).mean() 
        #print("CriticTensor: ", value_loss )
        value_loss.backward()
        torch.nn.utils.clip_grad_norm_(agent.critic_net.parameters(), gradient_clip)
        agent.critic_optimizer.step()
        
    print('Total score (averaged over agents) in episode #{} : {}'.format(e, np.mean(scores)))


Total score (averaged over agents) in episode #0 : 0.047499998938292265
Total score (averaged over agents) in episode #1 : 0.22199999503791332
Total score (averaged over agents) in episode #2 : 0.10749999759718776
Total score (averaged over agents) in episode #3 : 0.19649999560788273
Total score (averaged over agents) in episode #4 : 0.16949999621137976
Total score (averaged over agents) in episode #5 : 0.1629999963566661
Total score (averaged over agents) in episode #6 : 0.2094999953173101
Total score (averaged over agents) in episode #7 : 0.04649999896064401
Total score (averaged over agents) in episode #8 : 0.0754999983124435
Total score (averaged over agents) in episode #9 : 0.2524999943561852
Total score (averaged over agents) in episode #10 : 0.15749999647960067
Total score (averaged over agents) in episode #11 : 0.09399999789893627
Total score (averaged over agents) in episode #12 : 0.14799999669194222
Total score (averaged over agents) in episode #13 : 0.13849999690428377
Total